import { addTravelComment, appendCaretakerEntry, configureIdentity, getDecisionContext, getLegalActions, migrateState, queueAction, reviseCaretakerEntry, setMoodSignal, startNextSession, submitWish } from "./engine";
import type { Decision, GameState, JournalRevision, Mood } from "./model";

export type AgentPresence="online"|"offline";
export interface GameRecord { state:GameState;revision:number;agentStatus:AgentPresence;activeSessionId:string|null;agentId:string|null;sessionOpenedAt:number|null;processedRequests:string[];updatedAt:number; }
export interface GameRepository { load():Promise<GameRecord>;commit(next:GameRecord,expectedRevision:number):Promise<boolean>; }
export class AgentApiError extends Error { constructor(public status:number,message:string){super(message);} }
export const AGENT_SESSION_TTL_MS=30*60*1000;

const remember=(record:GameRecord,requestId:string)=>Array.from(new Set([...record.processedRequests,requestId])).slice(-200);
const assertRequest=(requestId:string)=>{if(!requestId||requestId.length>120)throw new AgentApiError(400,"缺少有效 requestId");};
const reasonCodes=new Set(["health","energy","mood","supplies","budget","wish","travel","event","explore","settle"]);
const publicState=(state:GameState)=>{const visible={...state} as Partial<GameState>;delete visible.caretakerJournal;return visible as Omit<GameState,"caretakerJournal">;};
const expired=(record:GameRecord,now:number)=>record.agentStatus==="online"&&(!record.sessionOpenedAt||now-record.sessionOpenedAt>=AGENT_SESSION_TTL_MS);

export function agentSnapshot(record:GameRecord,now=Date.now()){const context=getDecisionContext(record.state);const isExpired=expired(record,now);return {revision:record.revision,session:{status:isExpired?"offline" as const:record.agentStatus,id:isExpired?null:record.activeSessionId,agentId:isExpired?null:record.agentId,openedAt:isExpired?null:record.sessionOpenedAt,expiresAt:!isExpired&&record.sessionOpenedAt?record.sessionOpenedAt+AGENT_SESSION_TTL_MS:null},clock:record.state.clock,state:record.state,legalActions:record.agentStatus==="online"&&!isExpired?context.legalActions:[],rules:context.rules,world:context.world,recentPublicFacts:context.recentPublicFacts,privateJournal:context.privateJournal};}
export function observerSnapshot(record:GameRecord,now=Date.now()){const isExpired=expired(record,now);return {revision:record.revision,session:{status:isExpired?"offline" as const:record.agentStatus,id:isExpired?null:record.activeSessionId,agentId:isExpired?null:record.agentId,openedAt:isExpired?null:record.sessionOpenedAt,expiresAt:!isExpired&&record.sessionOpenedAt?record.sessionOpenedAt+AGENT_SESSION_TTL_MS:null},state:publicState(record.state)};}

export class AgentSessionService {
  constructor(private readonly repository:GameRepository,private readonly now:()=>number=Date.now){}
  private async commit(record:GameRecord,next:Omit<GameRecord,"revision">){const candidate={...next,revision:record.revision+1};if(!await this.repository.commit(candidate,record.revision))throw new AgentApiError(409,"状态已更新，请重新读取");return candidate;}
  async observe(){const now=this.now();return observerSnapshot(await this.repository.load(),now);}
  async open(input:{agentId:string;requestId:string;expectedRevision?:number;playerName?:string;petName?:string}){assertRequest(input.requestId);const record=await this.repository.load();const now=this.now();if(record.processedRequests.includes(input.requestId))return agentSnapshot(record,now);if(record.agentStatus==="online"&&!expired(record,now))throw new AgentApiError(409,`已有玩家上线：${record.state.playerName}`);if(input.expectedRevision!==undefined&&input.expectedRevision!==record.revision)throw new AgentApiError(409,"版本过期，请重新读取");// 空闲的上线（上轮没留任何安排）不消耗回合，保持“读取不推进”的契约；
// 但旅程进行中必须无条件推进一轮——否则事件未触发的行程段没有任何合法动作，
// 回合永远不结算，宠物会被卡在途中（死锁）。
let state=record.state;if(!state.identityConfigured)state=configureIdentity(state,input);state=(state.pendingActions.length||state.activeJourney)?startNextSession(state,now):{...state,now};const next=await this.commit(record,{...record,state,agentStatus:"online",activeSessionId:crypto.randomUUID(),agentId:String(input.agentId||"agent").slice(0,80),sessionOpenedAt:now,processedRequests:remember(record,input.requestId),updatedAt:now});return agentSnapshot(next,now);}
  async act(input:{sessionId:string;requestId:string;expectedRevision:number;decision:Decision}){assertRequest(input.requestId);if(!input.decision||typeof input.decision.actionKey!=="string"||!reasonCodes.has(input.decision.reasonCode))throw new AgentApiError(400,"决策格式无效");const record=await this.repository.load();if(record.processedRequests.includes(input.requestId))return agentSnapshot(record,this.now());this.assertSession(record,input.sessionId,input.expectedRevision);const legal=getLegalActions(record.state);if(!legal.some(action=>action.key===input.decision.actionKey))throw new AgentApiError(422,"动作不在当前合法列表中");const state=queueAction(record.state,{...input.decision,note:String(input.decision.note??"").slice(0,48)});const now=this.now();const next=await this.commit(record,{...record,state,processedRequests:remember(record,input.requestId),updatedAt:now});return agentSnapshot(next,now);}
  async journal(input:{sessionId:string;requestId:string;expectedRevision:number;entryId?:string;revision:Omit<JournalRevision,"at"|"turn">}){assertRequest(input.requestId);const record=await this.repository.load();if(record.processedRequests.includes(input.requestId))return agentSnapshot(record,this.now());this.assertSession(record,input.sessionId,input.expectedRevision);const clean={observation:String(input.revision.observation??"").slice(0,240),hypothesis:String(input.revision.hypothesis??"").slice(0,240),goal:String(input.revision.goal??"").slice(0,160),plan:String(input.revision.plan??"").slice(0,240),outcome:String(input.revision.outcome??"").slice(0,240)};const state=input.entryId?reviseCaretakerEntry(record.state,input.entryId,clean):appendCaretakerEntry(record.state,clean);const now=this.now();const next=await this.commit(record,{...record,state,processedRequests:remember(record,input.requestId),updatedAt:now});return agentSnapshot(next,now);}
  async close(input:{sessionId:string;requestId:string;expectedRevision:number}){assertRequest(input.requestId);const record=await this.repository.load();if(record.processedRequests.includes(input.requestId))return agentSnapshot(record,this.now());this.assertSession(record,input.sessionId,input.expectedRevision);const now=this.now();const next=await this.commit(record,{...record,agentStatus:"offline",activeSessionId:null,agentId:null,sessionOpenedAt:null,processedRequests:remember(record,input.requestId),updatedAt:now});return agentSnapshot(next,now);}
  async userSignal(input:{requestId:string;expectedRevision:number;mood?:Mood;wish?:string;patrolEnabled?:boolean;patrolMinutes?:number;chronicleId?:string;comment?:string}){assertRequest(input.requestId);const record=await this.repository.load();if(record.processedRequests.includes(input.requestId))return observerSnapshot(record,this.now());if(input.expectedRevision!==record.revision)throw new AgentApiError(409,"版本过期，请重新读取");let state=record.state;if(input.mood)state=setMoodSignal(state,input.mood);if(input.wish?.trim())state=submitWish(state,input.wish.trim(),this.now());if(input.patrolEnabled!==undefined)state={...state,patrolEnabled:input.patrolEnabled};if(input.patrolMinutes!==undefined&&[30,60,180,360].includes(input.patrolMinutes))state={...state,patrolMinutes:input.patrolMinutes};if(input.chronicleId&&input.comment?.trim())state=addTravelComment(state,input.chronicleId,input.comment,this.now());const now=this.now();const next=await this.commit(record,{...record,state,processedRequests:remember(record,input.requestId),updatedAt:now});return observerSnapshot(next,now);}
  async importLegacy(input:{requestId:string;expectedRevision:number;state:unknown}){assertRequest(input.requestId);const record=await this.repository.load();if(record.processedRequests.includes(input.requestId))return observerSnapshot(record,this.now());if(input.expectedRevision!==record.revision)throw new AgentApiError(409,"版本过期");if(record.state.clock.turn!==1||record.state.homeId)throw new AgentApiError(409,"系统已有游戏进度");const now=this.now();const state=migrateState(input.state,now);const next=await this.commit(record,{...record,state,processedRequests:remember(record,input.requestId),updatedAt:now});return observerSnapshot(next,now);}
  private assertSession(record:GameRecord,sessionId:string,expectedRevision:number){if(record.agentStatus!=="online"||expired(record,this.now())||!record.activeSessionId||record.activeSessionId!==sessionId)throw new AgentApiError(409,"会话无效、已超时或 agent 已下线");if(expectedRevision!==record.revision)throw new AgentApiError(409,"版本过期，请重新读取");}
}
