/* PRNG helpers intentionally assign one tuple member once while advancing mutable local state. */
/* eslint-disable prefer-const */
import type { ActionOption, CarePlan, Decision, EventFollowUp, GameState, InventoryItem, ItemDrop, JournalRevision, LegacyGameStateV1, Mood, PetStats, PlaceId, PublicLogEntry, RuleContract, TravelMoment, WeightedEvent } from "./model";
import { clockFor, createShop, getPlace, getRoute, otherEnd, PLACE_EVENT_TRIGGER_CHANCES, PLACES, ROUTE_EVENT_TABLE, ROUTE_EVENT_TRIGGER_CHANCES, routeCost, routesFrom, seasonFor, weatherFor } from "./world";

export const RULE_CONTRACT:RuleContract={
  time:{turnsPerDay:2,daysPerMonth:10,settlement:"next_login"},
  authority:["外部 agent 玩家可在同一轮安排任意数量的合法动作并自行决定何时下线","动作只进入待结算队列，本轮不会返回状态变化或随机结果","下次上线由规则引擎统一结算，agent 不得生成概率、掉落、费用或数值结果","愿望与心情只是判断信号，不是命令"],
  travel:{growthDistanceBands:[{minExperience:0,maxDistance:40},{minExperience:15,maxDistance:60},{minExperience:30,maxDistance:999}],lowGrowthCooldownTurns:2},
  itemUse:"所有道具有固定可用次数；每次实际生效时消耗 1 次，剩余 0 次后移出库存。",
  resultVisibility:"外部 agent 在安排时只能看到条件、成本区间、概率表和待结算队列；只能在下一轮读取程序生成的事实结果。",
};

const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const withStats=(state:GameState,delta:Partial<PetStats>):GameState=>({...state,stats:Object.fromEntries(Object.entries(state.stats).map(([key,value])=>[key,clamp(value+(delta[key as keyof PetStats]??0))])) as unknown as PetStats});
const remaining=(state:GameState,id:string)=>state.inventory.find(item=>item.id===id)?.usesRemaining??0;
const reservedUses=(state:GameState,id:string)=>state.pendingActions.filter(q=>(q.option.actionId==="feed"&&q.option.itemId===id)||(q.option.actionId==="treat"&&["bandage","medicine","herb","mild-dose"].includes(id))||(q.option.actionId==="depart_trip"&&id==="trip-kit")||(q.option.actionId==="resolve_event"&&q.option.itemId===id)).length;
const has=(state:GameState,id:string)=>remaining(state,id)-reservedUses(state,id)>0;
const foodEffect=(id:string):Partial<PetStats>=>id==="meal"?{satiety:36,health:2,mood:1}:id==="snack"?{satiety:22,mood:3}:{satiety:18,mood:2};
const feedActions=(state:GameState):ActionOption[]=>state.stats.satiety>=82?[]:state.inventory.filter(item=>item.kind==="food"&&has(state,item.id)).map(item=>({key:item.id==="snack"?"feed":`feed:${item.id}`,actionId:"feed",itemId:item.id,label:item.id==="snack"?"准备点心":`准备${item.name}`,description:`预留 1 次${item.name}使用`,cost:0,hiddenConsequences:["下轮生效","道具次数-1"]}));
const prioritizeCriticalCare=(state:GameState,actions:ActionOption[]):ActionOption[]=>{const pending=state.pendingActions.some(item=>item.option.actionId==="feed"||item.option.actionId==="rest"||(item.option.actionId==="buy"&&["snack","meal"].includes(item.option.itemId??"")));if((state.stats.satiety<=20||state.stats.energy<=20)&&pending)return [];if(state.stats.satiety<=20){const food=actions.filter(action=>action.actionId==="feed"||(action.actionId==="buy"&&["snack","meal"].includes(action.itemId??""))||action.actionId==="emergency_relief");if(food.length)return food;}if(state.stats.energy<=20){const recovery=actions.filter(action=>action.actionId==="rest"||action.actionId==="feed"||(action.actionId==="buy"&&["snack","meal"].includes(action.itemId??""))||action.actionId==="emergency_relief");if(recovery.length)return recovery;}return actions;};
const committedMoney=(state:GameState)=>state.pendingActions.reduce((sum,q)=>sum+q.option.cost,0);
const availableMoney=(state:GameState)=>state.money-committedMoney(state);
const addItem=(state:GameState,item:InventoryItem):GameState=>{const found=state.inventory.find(i=>i.id===item.id);return {...state,inventory:found?state.inventory.map(i=>i.id===item.id?{...i,usesRemaining:i.usesRemaining+item.usesRemaining,maxUses:i.maxUses+item.maxUses}:i):[...state.inventory,item]};};
const personalize=(template:string,state:GameState)=>template.replaceAll("{playerName}",state.playerName).replaceAll("{petName}",state.petName);
export function collectPlaceDrop(input:GameState,item:ItemDrop,sourcePlaceId:PlaceId):GameState{
  const name=personalize(item.interaction?.titleTemplate??item.name,input);
  let state=addItem(input,{id:item.itemId,name,kind:item.kind,usesRemaining:item.uses,maxUses:item.uses});
  state={...state,collections:Array.from(new Set([...state.collections,name]))};
  if(item.interaction){
    const sourcePlaceName=getPlace(sourcePlaceId).name;
    state={...state,keepsakes:[{id:`keepsake-${state.clock.turn}-${state.rngSeed}-${item.itemId}`,itemId:item.itemId,name,body:personalize(item.interaction.bodyTemplate,state),kind:item.interaction.kind,sourcePlaceId,sourcePlaceName,acquiredTurn:state.clock.turn},...(state.keepsakes??[])].slice(0,80)};
  }
  return state;
}
const consumeItem=(state:GameState,id:string):GameState=>({...state,inventory:state.inventory.map(i=>i.id===id?{...i,usesRemaining:i.usesRemaining-1}:i).filter(i=>i.usesRemaining>0)});
const idHash=(text:string)=>{let value=2166136261;for(let index=0;index<text.length;index++)value=Math.imul(value^text.charCodeAt(index),16777619);return (value>>>0).toString(36);};
const publicFact=(state:GameState,entry:Omit<PublicLogEntry,"id"|"at"|"turn">):GameState=>({...state,publicLog:[{...entry,id:`fact-${state.clock.turn}-${idHash(`${state.publicLog[0]?.id??"start"}|${entry.title}|${state.rngSeed}`)}`,at:state.now,turn:state.clock.turn},...state.publicLog].slice(0,160)});
const ledger=(state:GameState,category:GameState["ledger"][number]["category"],amount:number,note:string):GameState=>({...state,ledger:[{id:`cash-${state.clock.turn}-${idHash(`${state.ledger[0]?.id??"start"}|${category}|${note}`)}`,at:state.now,turn:state.clock.turn,category,amount,balance:state.money,note},...state.ledger].slice(0,140)});
const completeStep=(plan:CarePlan|null,id:string)=>plan?{...plan,steps:plan.steps.map(step=>step.id===id?{...step,status:"完成" as const}:step)}:null;
const random=(state:GameState)=>{const seed=(state.rngSeed*1664525+1013904223)>>>0;return [seed/2**32,{...state,rngSeed:seed}] as const;};
const randomInt=(state:GameState,[min,max]:[number,number])=>{let roll,next;[roll,next]=random(state);return [Math.round(min+roll*(max-min)),next] as const;};

export function createInitialState(now=Date.now()):GameState{return {version:4,petName:"小宠物",playerName:"饲养者",identityConfigured:false,startedAt:now,now,clock:clockFor(1),nextPatrolAt:now+3_600_000,patrolEnabled:true,patrolMinutes:60,money:100,debt:0,moodSignal:"平静",wish:null,homeId:null,positionId:null,homeChoiceReason:"",condition:"健康",weather:"晴",season:"春",stats:{health:78,mood:70,energy:70,satiety:65,activity:55,experience:0},previousStats:null,inventory:[],shop:[],publicLog:[{id:"welcome",at:now,turn:1,category:"系统",title:"第 1 轮上线",text:"user 变成你的小宠物啦～第一次上线时，请先给自己和小宠物取个名字。"}],caretakerJournal:[{id:"care-0",createdAt:now,revisions:[{at:now,turn:1,observation:"还没有固定住址，资金完整。",hypothesis:"交通与应急能力会影响前期稳定性。",goal:"选择可持续的起点。",plan:"先确定彼此的称呼，再比较住房、医疗、商店、地点事件和路线。",outcome:"尚未结算。"}]}],ledger:[],plan:null,strategy:{riskTolerance:.38,reserveTarget:28,shortTermGoal:"安顿下来",longTermGoal:"在安全与新鲜体验之间保持余地",budgetStyle:"均衡"},preferenceHypotheses:[{trait:"喜欢自然环境",confidence:.35,evidence:[]}],delayedEffects:[],activeEvents:[],pendingActions:[],recentEventIds:[],collections:[],keepsakes:[],visitedPlaces:[],currentRouteId:null,activeJourney:null,travelChronicles:[],lastSettledDecisions:[],lastTravelTurn:null,consecutiveTrips:0,shopCycle:0,rngSeed:1};}

function uniqueIds<T extends {id:string}>(items:T[]):T[]{const used=new Set<string>();return items.map((item,index)=>{let id=item.id;while(used.has(id))id=`${item.id}-duplicate-${index}`;used.add(id);return id===item.id?item:{...item,id};});}

export function migrateState(raw:GameState|LegacyGameStateV1|unknown,now=Date.now()):GameState{
  if(raw&&typeof raw==="object"&&[(raw as {version?:number}).version].some(version=>version===3||version===4)){const old=raw as GameState&{pendingActions?:Array<GameState["pendingActions"][number]&{decision:Decision&{reason?:string}}>};const base={...createInitialState(now),...old,version:4 as const,now};return {...base,publicLog:uniqueIds(base.publicLog??[]),ledger:uniqueIds(base.ledger??[]),caretakerJournal:uniqueIds(base.caretakerJournal??[]),lastSettledDecisions:base.lastSettledDecisions??[],activeJourney:base.activeJourney??null,travelChronicles:base.travelChronicles??[],pendingActions:(base.pendingActions??[]).map(queued=>({...queued,decision:queued.decision.reasonCode?queued.decision:{actionKey:queued.decision.actionKey,reasonCode:"settle" as const,note:(queued.decision as Decision&{reason?:string}).reason?.slice(0,48)??"旧存档安排",continueSession:queued.decision.continueSession}}))};}
  if(raw&&typeof raw==="object"){const old=raw as Record<string,unknown>;const base=createInitialState(now);const oldInventory=(old.inventory as Array<Record<string,unknown>>|undefined)??[];const oldLogs=(old.publicLog as Array<Record<string,unknown>>|undefined)??(old.journal as Array<Record<string,unknown>>|undefined)??[];const home=(old.homeId as PlaceId|undefined)??((old.version===1)?"station":null);return {...base,petName:typeof old.petName==="string"?old.petName:base.petName,playerName:typeof old.playerName==="string"?old.playerName:base.playerName,identityConfigured:Boolean(old.identityConfigured),homeId:home,positionId:(old.positionId as PlaceId|undefined)??home,homeChoiceReason:(old.homeChoiceReason as string|undefined)??"旧存档已迁移到轮次制。",money:typeof old.money==="number"?old.money:base.money,debt:typeof old.debt==="number"?old.debt:0,stats:(old.stats as PetStats|undefined)??(home?getPlace(home).startingStats:base.stats),inventory:oldInventory.map(item=>({id:String(item.id),name:String(item.name),kind:item.kind as InventoryItem["kind"],usesRemaining:Number(item.usesRemaining??item.quantity??1),maxUses:Number(item.maxUses??item.quantity??1)})),publicLog:oldLogs.map((entry,index)=>({id:String(entry.id??`old-${index}`),at:Number(entry.at??now),turn:1,category:(entry.category??"行动") as PublicLogEntry["category"],title:String(entry.title??"旧记录"),text:String(entry.text??"")})),shop:home?createShop(home,0,1):[]};}
  return createInitialState(now);
}

// Identity fields intentionally strip ASCII control characters.
// eslint-disable-next-line no-control-regex
const identityName=(value:unknown,fallback:string)=>String(value??"").replace(/[\u0000-\u001f\u007f]/g,"").trim().slice(0,16)||fallback;
export function configureIdentity(state:GameState,input:{agentId:string;playerName?:string;petName?:string}):GameState{
  if(state.identityConfigured)return state;
  const playerName=identityName(input.playerName,identityName(input.agentId,"饲养者"));
  const petName=identityName(input.petName,state.petName||"小宠物");
  return publicFact({...state,playerName,petName,identityConfigured:true},{category:"系统",title:"彼此的称呼确定了",text:`${playerName}把 user 接进小窝，给小宠物取名为“${petName}”；从现在起，页面、日志和收藏都会使用这两个名字。`});
}

function maxTravelDistance(experience:number){return [...RULE_CONTRACT.travel.growthDistanceBands].reverse().find(b=>experience>=b.minExperience)!.maxDistance;}
export function getLegalActions(state:GameState):ActionOption[]{
  if(!state.homeId){if(state.pendingActions.some(q=>q.option.actionId==="choose_home"))return [];return PLACES.filter(p=>availableMoney(state)>=p.housingCost).map(place=>({key:`choose_home:${place.id}`,actionId:"choose_home",targetPlaceId:place.id,label:`住进${place.name}`,description:`住房 ${place.housingCost}；${place.summary}`,cost:place.housingCost,hiddenConsequences:[`初始属性:${JSON.stringify(place.startingStats)}`,`事件概率:${place.eventTable.map(e=>`${e.name}${e.weight}%`).join("、")}`,`数字收益:${JSON.stringify(place.numericYield)}`,`道具池:${place.itemPool.map(i=>`${i.name}/${i.uses}次`).join("、")}`]}));}
  const funds=availableMoney(state);const actions:ActionOption[]=state.activeJourney?[]:[{key:"observe",actionId:"observe",label:"观察状态",description:"安排一次观察，结果下轮写入事实",cost:0,hiddenConsequences:["成长小幅增加","触发当地事件"]},{key:"clean",actionId:"clean",label:"整理小窝",description:"安排清洁，下轮才知道效果",cost:0,hiddenConsequences:["健康和心情可能改善"]},{key:"photo_diary",actionId:"photo_diary",label:"记录今天",description:"安排拍照与公开记录",cost:0,hiddenConsequences:["成长小幅增加"]}];
  actions.push(...feedActions(state));
  for(const active of state.activeEvents){const alreadyResponding=state.pendingActions.some(q=>q.option.activeEventId===active.id);if(!alreadyResponding)for(const response of active.responses??[])actions.push({key:`respond_event:${active.id}:${response.id}`,actionId:"respond_event",activeEventId:active.id,eventResponseId:response.id,label:`${active.name}：${response.label}`,description:response.description,cost:0,hiddenConsequences:[`数值:${JSON.stringify(response.statDelta)}`,`金钱:${response.moneyDelta}`,`持续轮数变化:${response.durationDelta}`]});const itemId=active.manualEndItemIds.find(id=>has(state,id));if(itemId&&!alreadyResponding)actions.push({key:`resolve_event:${active.id}:${itemId}`,actionId:"resolve_event",activeEventId:active.id,itemId,label:`处理${active.name}`,description:`消耗 ${state.inventory.find(i=>i.id===itemId)?.name??itemId} 1 次以提前结束`,cost:0,hiddenConsequences:["下轮结算时结束持续影响","道具次数-1","可能中断后续事件链"]});}
  if(state.activeJourney?.stage==="play"&&!state.activeJourney.pendingContinue&&state.stats.energy>=45&&state.condition==="健康"&&remaining(state,"trip-kit")>0){const origin=state.activeJourney.destinationId;for(const route of routesFrom(origin)){const target=otherEnd(route,origin);const cost=routeCost(route,state.homeId!);if(availableMoney(state)>=cost)actions.push({key:`continue_trip:${route.id}`,actionId:"continue_trip",routeId:route.id,targetPlaceId:target,label:`续行到${getPlace(target).name}`,description:`途中转场（预算 ${cost}，旅行用品 1 次），不先回家`,cost,hiddenConsequences:[`路线风险:${Math.round(route.risk*100)}%`,`下一站事件:${getPlace(target).eventTable.map(e=>`${e.name}${e.weight}%`).join("、")}`,`转场后仍可再续行或直接返家`]});}}
  if(state.activeJourney)return prioritizeCriticalCare(state,actions);
  if(state.stats.mood<88)actions.push({key:"comfort",actionId:"comfort",label:"安静陪伴",description:"安排陪伴，下轮观察反应",cost:0,hiddenConsequences:["心情可能改善"]});
  if(state.stats.energy<88)actions.push({key:"rest",actionId:"rest",label:"安排休息",description:"把恢复排进本轮",cost:0,hiddenConsequences:["精力恢复","活跃可能下降"]});
  if(state.condition==="轻伤"||state.condition==="生病"){if(state.plan?.kind!=="recovery"||state.plan.steps.find(s=>s.id==="diagnose")?.status!=="完成")actions.push({key:"diagnose",actionId:"diagnose",label:"安排诊断",description:"下轮确认状况",cost:0,hiddenConsequences:["建立恢复计划"]});if(["bandage","medicine","herb","mild-dose"].some(id=>has(state,id)))actions.push({key:"treat",actionId:"treat",label:"安排居家处理",description:"预留合适道具 1 次",cost:0,hiddenConsequences:["进入恢复期","道具次数-1"]});const clinicCost=Math.max(12,32-getPlace(state.homeId).medicalLevel*3);if(funds>=clinicCost)actions.push({key:"visit_clinic",actionId:"visit_clinic",label:"预约诊所",description:"预留医疗费用",cost:clinicCost,hiddenConsequences:["下轮得到可靠治疗"]});}else if(state.condition==="健康"&&state.stats.energy>=48)actions.push({key:"train",actionId:"train",label:"安排轻量活动",description:"安排活动并等待反馈",cost:0,hiddenConsequences:["成长与活跃增加","消耗精力饱腹"]});
  for(const offer of state.shop){const reserved=state.pendingActions.filter(q=>q.option.actionId==="buy"&&q.option.itemId===offer.itemId).length;if(offer.stock-reserved>0&&funds>=offer.price)actions.push({key:`buy:${offer.itemId}`,actionId:"buy",itemId:offer.itemId,label:`预订${offer.name}`,description:`锁定价格 ${offer.price}，含 ${offer.uses} 次使用`,cost:offer.price,hiddenConsequences:["下轮扣款入库",`可用次数:${offer.uses}`]});}
  if(state.homeId&&!state.activeJourney&&!state.pendingActions.some(q=>q.option.actionId==="move_home"))for(const route of routesFrom(state.homeId)){const target=otherEnd(route,state.homeId);const place=getPlace(target);const cost=2*place.housingCost;if(funds>=cost)actions.push({key:`move_home:${target}`,actionId:"move_home",targetPlaceId:target,label:`搬家到${place.name}`,description:`搬家费 ${cost}（${place.housingCost} 的 2 倍），交通直达`,cost,hiddenConsequences:[`住房价:${place.housingCost}`,`事件概率:${place.eventTable.map(e=>`${e.name}${e.weight}%`).join("、")}`,`数字收益:${JSON.stringify(place.numericYield)}`,`道具池:${place.itemPool.map(i=>`${i.name}/${i.uses}次`).join("、")}`]});}
  const origin=state.positionId??state.homeId;const cooldownBlocked=state.stats.experience<50&&state.lastTravelTurn!==null&&state.clock.turn-state.lastTravelTurn<RULE_CONTRACT.travel.lowGrowthCooldownTurns;
  if(!state.plan&&!state.pendingActions.some(q=>q.option.actionId==="plan_trip")&&state.condition==="健康"&&!state.currentRouteId&&!cooldownBlocked)for(const route of routesFrom(origin)){const target=otherEnd(route,origin);if(route.distance<=maxTravelDistance(state.stats.experience))actions.push({key:`plan_trip:${route.id}`,actionId:"plan_trip",routeId:route.id,targetPlaceId:target,label:`规划前往${getPlace(target).name}`,description:`${route.distance}km，需 ${route.travelTurns} 轮，预算 ${routeCost(route,state.homeId)}`,cost:0,hiddenConsequences:[`路线风险:${Math.round(route.risk*100)}%`,`地点事件:${getPlace(target).eventTable.map(e=>`${e.name}${e.weight}%`).join("、")}`,`可能道具:${getPlace(target).itemPool.map(i=>i.name).join("、")}`]});}
  if(state.plan?.kind==="trip"&&state.plan.targetPlaceId){const route=routesFrom(origin).find(r=>otherEnd(r,origin)===state.plan!.targetPlaceId);if(route){const checked=state.plan.steps.find(s=>s.id==="health")?.status==="完成";if(!checked)actions.push({key:"check_health",actionId:"check_health",label:"安排出发前检查",description:"下轮确认健康、精力、饱腹和天气",cost:0,hiddenConsequences:["条件不符则无法出发"]});if(checked&&has(state,"trip-kit")&&state.stats.health>=65&&state.stats.energy>=55&&state.stats.satiety>=35&&funds>=routeCost(route,state.homeId))actions.push({key:`depart_trip:${route.id}`,actionId:"depart_trip",routeId:route.id,targetPlaceId:state.plan.targetPlaceId,label:"安排启程",description:"预留差旅费和旅行用品 1 次",cost:routeCost(route,state.homeId),hiddenConsequences:["下轮起才揭晓路线与地点后果"]});}actions.push({key:"review_plan",actionId:"review_plan",label:"修正旅行计划",description:"根据已知事实修正步骤",cost:0,hiddenConsequences:["只更新私人计划"]});}
  if(funds<5)actions.push({key:"emergency_relief",actionId:"emergency_relief",label:"申请基础救济",description:"避免经济死锁",cost:0,hiddenConsequences:["下轮获得18","债务+8"]});
  return prioritizeCriticalCare(state,actions);
}

const reasonText:Record<Decision["reasonCode"],string>={health:"优先稳定健康",energy:"保留精力余量",mood:"回应情绪信号",supplies:"补足必要物资",budget:"控制预算与应急金",wish:"评估 user 的愿望",travel:"推进多轮旅行计划",event:"处理当前事件",explore:"收集新信息",settle:"安顿与建立基础"};
function actionNarration(state:GameState,option:ActionOption,decision:Decision){return `${state.playerName}选择“${option.label}”：${reasonText[decision.reasonCode]}。${decision.note?`备注：${decision.note}。`:""}`;}
function writeCaretaker(state:GameState,decision:Decision,outcome:string,option?:ActionOption):GameState{const place=state.positionId?getPlace(state.positionId).name:state.activeJourney?`前往${getPlace(state.activeJourney.destinationId).name}`:"小窝";const revision:JournalRevision={at:state.now,turn:state.clock.turn,observation:`${place}；健康 ${state.stats.health}，精力 ${state.stats.energy}，心情 ${state.stats.mood}，余额 ${state.money}。`,hypothesis:reasonText[decision.reasonCode],goal:decision.note||reasonText[decision.reasonCode],plan:option?`已安排“${option.label}”，下轮根据事实复盘。`:"等待合法动作。",outcome};return {...state,caretakerJournal:[{id:`care-${state.clock.turn}-${state.caretakerJournal.length}`,createdAt:state.now,revisions:[revision]},...state.caretakerJournal].slice(0,100)};}
export function reviseCaretakerEntry(state:GameState,entryId:string,changes:Partial<JournalRevision>):GameState{return {...state,caretakerJournal:state.caretakerJournal.map(entry=>entry.id===entryId?{...entry,revisions:[...entry.revisions,{...entry.revisions.at(-1)!,...changes,at:state.now,turn:state.clock.turn}]}:entry)};}

export function queueAction(input:GameState,decision:Decision):GameState{const normalized={...decision,note:(decision.note??"").slice(0,48)};const option=getLegalActions(input).find(action=>action.key===normalized.actionKey);if(!option)return writeCaretaker(input,normalized,"安排已被规则拦下，没有占用资源。");const queued={id:`queued-${input.clock.turn}-${input.pendingActions.length}`,turn:input.clock.turn,option,decision:normalized};return writeCaretaker({...input,pendingActions:[...input.pendingActions,queued],wish:input.wish?{...input.wish,considered:true}:null},normalized,`已安排“${option.label}”，结果将在下一次上线时揭晓。`,option);}
export const applyAction=queueAction;

function settleQueuedAction(input:GameState,queued:GameState["pendingActions"][number]):GameState{const {option,decision}=queued;let state=input;
  const narration=actionNarration(state,option,decision);
  switch(option.actionId){
    case "choose_home":{const place=getPlace(option.targetPlaceId!);if(state.homeId||state.money<place.housingCost)break;state={...state,homeId:place.id,positionId:place.id,homeChoiceReason:`${reasonText[decision.reasonCode]}：${decision.note}`,money:state.money-place.housingCost,stats:place.startingStats,shop:createShop(place.id,state.shopCycle,state.rngSeed),visitedPlaces:[place.id],strategy:{...state.strategy,shortTermGoal:"建立应急储备并熟悉周边"}};state=ledger(state,"住房",-place.housingCost,`入住${place.name}`);state=publicFact(state,{category:"系统",title:`${state.playerName}选择了${place.name}`,text:narration,moneyDelta:-place.housingCost});break;}
    case "move_home":{const place=getPlace(option.targetPlaceId!);if(!state.homeId||state.homeId===place.id||state.money<option.cost||state.activeJourney)break;state={...state,homeId:place.id,positionId:place.id,homeChoiceReason:`搬家：${reasonText[decision.reasonCode]}${decision.note?`（${decision.note}）`:""}`,money:state.money-option.cost,shop:createShop(place.id,state.shopCycle,state.rngSeed),visitedPlaces:Array.from(new Set([...state.visitedPlaces,place.id]))};state=ledger(state,"住房",-option.cost,`搬家至${place.name}（${place.housingCost} 的 2 倍）`);state=publicFact(state,{category:"系统",title:`${state.playerName}搬到了${place.name}`,text:narration,moneyDelta:-option.cost});break;}
    case "observe":state=publicFact(withStats(state,{experience:1}),{category:"行动",title:"观察结果已记录",text:narration,deltas:{experience:1}});break;
    case "comfort":state=publicFact(withStats(state,{mood:12,energy:2}),{category:"行动",title:"陪伴有了回应",text:narration,deltas:{mood:12,energy:2}});break;
    case "feed":{const itemId=option.itemId??"snack";const itemName=state.inventory.find(item=>item.id===itemId)?.name??"食物";const deltas=foodEffect(itemId);if(remaining(state,itemId)>0)state=publicFact(withStats(consumeItem(state,itemId),deltas),{category:"行动",title:`${itemName}喂食完成`,text:narration,deltas});break;}
    case "clean":state=publicFact(withStats(state,{health:2,mood:2}),{category:"行动",title:"小窝整理完成",text:narration,deltas:{health:2,mood:2}});break;
    case "rest":state=publicFact(withStats(state,{energy:22,health:3,activity:-2}),{category:"状态",title:"休息结果揭晓",text:narration,deltas:{energy:22,health:3,activity:-2}});break;
    case "train":state=publicFact(withStats(state,{energy:-10,satiety:-6,activity:10,experience:5}),{category:"行动",title:"轻量活动完成",text:narration,deltas:{energy:-10,satiety:-6,activity:10,experience:5}});break;
    case "diagnose":state={...state,plan:{id:`recovery-${state.clock.turn}`,kind:"recovery",goal:"安全恢复健康",createdAt:state.now,steps:[{id:"diagnose",label:"确认状况",status:"完成"},{id:"care",label:"治疗或就医",status:"待办"},{id:"recover",label:"完成恢复",status:"待办"}]}};state=publicFact(state,{category:"状态",title:"诊断结果已确认",text:narration});break;
    case "treat":{const id=["bandage","medicine","herb","mild-dose"].find(x=>remaining(state,x)>0);if(id){state=consumeItem(state,id);state={...withStats(state,{health:12,energy:5}),condition:"恢复中",plan:completeStep(state.plan,"care"),delayedEffects:[...state.delayedEffects,{id:`recover-${state.clock.turn}`,dueTurn:state.clock.turn+1,kind:"recovery_complete",severity:0,source:"居家处理"}]};state=publicFact(state,{category:"状态",title:"进入恢复期",text:narration,deltas:{health:12,energy:5}});}break;}
    case "visit_clinic":if(state.money>=option.cost){state={...state,money:state.money-option.cost,condition:"恢复中",plan:completeStep(state.plan,"care"),delayedEffects:[...state.delayedEffects,{id:`recover-${state.clock.turn}`,dueTurn:state.clock.turn+1,kind:"recovery_complete",severity:0,source:"诊所治疗"}]};state=ledger(state,"医疗",-option.cost,"诊所检查与治疗");state=publicFact(withStats(state,{health:22}),{category:"费用",title:"诊所结果已返回",text:narration,moneyDelta:-option.cost,deltas:{health:22}});}break;
    case "buy":{const offer=state.shop.find(o=>o.itemId===option.itemId);if(offer&&offer.stock>0&&state.money>=offer.price){state={...state,money:state.money-offer.price,shop:state.shop.map(o=>o.itemId===offer.itemId?{...o,stock:o.stock-1}:o)};state=addItem(state,{id:offer.itemId,name:offer.name,kind:offer.kind,usesRemaining:offer.uses,maxUses:offer.uses});if(offer.itemId==="trip-kit")state={...state,plan:completeStep(state.plan,"supplies")};state=ledger(state,"采购",-offer.price,`购买${offer.name}（${offer.uses}次）`);state=publicFact(state,{category:"费用",title:`购入${offer.name}`,text:`${narration} 可使用 ${offer.uses} 次。`,moneyDelta:-offer.price});}break;}
    case "plan_trip":state={...state,plan:{id:`trip-${state.clock.turn}`,kind:"trip",goal:`前往${getPlace(option.targetPlaceId!).name}`,targetPlaceId:option.targetPlaceId,createdAt:state.now,steps:[{id:"save",label:"预留差旅费",status:state.money>=routeCost(getRoute(option.routeId!),state.homeId!)?"完成":"待办"},{id:"supplies",label:"准备旅行用品",status:remaining(state,"trip-kit")>0?"完成":"待办"},{id:"health",label:"出发前检查",status:"待办"},{id:"depart",label:"选择路线并出发",status:"待办"}]}};state=publicFact(state,{category:"旅行",title:"旅行计划已形成",text:narration});break;
    case "check_health":state={...state,plan:completeStep(state.plan,"health")};state=publicFact(state,{category:"状态",title:"出发检查结果可用",text:narration});break;
    case "depart_trip":{const route=getRoute(option.routeId!);if(state.money<option.cost||remaining(state,"trip-kit")<1)break;const target=option.targetPlaceId!;const origin=state.positionId!;const moment:TravelMoment={turn:state.clock.turn,stage:"outbound",title:"出发",text:`从${getPlace(origin).name}前往${getPlace(target).name}。`,agentHandling:narration};state={...consumeItem(state,"trip-kit"),money:state.money-option.cost,positionId:null,currentRouteId:route.id,activeJourney:{id:`journey-${state.clock.turn}-${state.rngSeed}`,routeId:route.id,destinationId:target,startedTurn:state.clock.turn,stage:"outbound",remainingTurns:route.travelTurns,overnightCount:0,incidentRiskMultiplier:1,moments:[moment]},lastTravelTurn:state.clock.turn,consecutiveTrips:state.lastTravelTurn!==null&&state.clock.turn-state.lastTravelTurn<=2?state.consecutiveTrips+1:1,plan:completeStep(state.plan,"depart")};state=ledger(state,"旅行",-option.cost,`${getPlace(origin).name}→${getPlace(target).name}往返预算`);state=publicFact(state,{category:"旅行",title:"已离开小窝",text:`${narration} 去程 ${route.travelTurns} 轮，到达后至少游玩 1 轮，最后返家。`,moneyDelta:-option.cost});break;}
    case "continue_trip":{const journey=state.activeJourney;if(!journey||journey.stage!=="play"||journey.pendingContinue||state.money<option.cost||remaining(state,"trip-kit")<1)break;const target=option.targetPlaceId!;const route=getRoute(option.routeId!);state={...consumeItem(state,"trip-kit"),money:state.money-option.cost,activeJourney:{...journey,pendingContinue:{routeId:route.id,destinationId:target,cost:option.cost}}};state=appendJourneyMoment(state,{turn:state.clock.turn,stage:"outbound",title:`续行前往${getPlace(target).name}`,text:`决定不先回家，直接转场。`,agentHandling:narration});state=ledger(state,"旅行",-option.cost,`转场：${getPlace(journey.destinationId).name}→${getPlace(target).name}`);state=publicFact(state,{category:"旅行",title:`${state.playerName}选择续行转场`,text:narration,moneyDelta:-option.cost});break;}
    case "review_plan":state=publicFact(state,{category:"行动",title:`${state.playerName}修正了安排`,text:narration});break;
    case "photo_diary":state=publicFact(withStats(state,{experience:2,mood:2}),{category:"行动",title:"照片写入宠物日志",text:narration,deltas:{experience:2,mood:2}});break;
    case "respond_event":{const active=state.activeEvents.find(e=>e.id===option.activeEventId);const response=active?.responses?.find(r=>r.id===option.eventResponseId);if(active&&response){state=withStats(state,response.statDelta);if(response.moneyDelta){state={...state,money:Math.max(0,state.money+response.moneyDelta)};state=ledger(state,"探索",response.moneyDelta,`${active.name}：${response.label}`);}const remainingTurns=Math.max(0,active.remainingTurns+response.durationDelta);const rest=remainingTurns===0?state.activeEvents.filter(e=>e.id!==active.id):state.activeEvents.map(e=>e.id===active.id?{...e,remainingTurns}:e);const stillUnwell=rest.some(e=>e.kind==="accident"||e.kind==="sickness");state={...state,activeEvents:rest,condition:!stillUnwell&&(active.kind==="accident"||active.kind==="sickness")?"健康":state.condition};state=publicFact(state,{category:"行动",title:`${state.playerName}应对了${active.name}`,text:`选择“${response.label}”：${response.description}；事件还剩 ${remainingTurns} 轮。`,deltas:response.statDelta,moneyDelta:response.moneyDelta||undefined});}break;}
    case "resolve_event":{const active=state.activeEvents.find(e=>e.id===option.activeEventId);if(active&&option.itemId&&remaining(state,option.itemId)>0){const itemName=state.inventory.find(i=>i.id===option.itemId)?.name??option.itemId;state=consumeItem(state,option.itemId);const rest=state.activeEvents.filter(e=>e.id!==active.id);const stillUnwell=rest.some(e=>e.kind==="accident"||e.kind==="sickness");state={...state,activeEvents:rest,condition:!stillUnwell&&(active.kind==="accident"||active.kind==="sickness")?"健康":state.condition};state=publicFact(state,{category:"行动",title:`${active.name}已提前结束`,text:`${state.playerName}使用${itemName}处理了持续事件，后续每轮影响不再发生。`});}break;}
    case "emergency_relief":state={...state,money:state.money+18,debt:state.debt+8};state=ledger(state,"救济",18,"基础照料救济");state=publicFact(state,{category:"费用",title:"基础救济到账",text:"规则引擎避免了经济死锁，后续收入会自动偿还一部分。",moneyDelta:18});break;
  }
  if(state.activeJourney&&(option.actionId==="feed"||option.actionId==="respond_event"||option.actionId==="resolve_event"))state=appendJourneyMoment(state,{turn:state.clock.turn,stage:state.activeJourney.stage,title:`${state.playerName}处理：${option.label}`,text:reasonText[decision.reasonCode],agentHandling:narration});
  return state;
}

function appendJourneyMoment(state:GameState,moment:TravelMoment):GameState{return state.activeJourney?{...state,activeJourney:{...state.activeJourney,moments:[...state.activeJourney.moments,moment]}}:state;}

function activateEvent(input:GameState,event:WeightedEvent|EventFollowUp,source:string):GameState{const recentEventIds=[event.id,...(input.recentEventIds??[]).filter(id=>id!==event.id)].slice(0,12);if(event.durationTurns<=1)return {...input,recentEventIds};const existing=input.activeEvents.find(active=>active.definitionId===event.id);if(existing)return {...input,recentEventIds,activeEvents:input.activeEvents.map(active=>active.id===existing.id?{...active,remainingTurns:Math.max(active.remainingTurns,event.durationTurns)}:active)};return {...input,recentEventIds,activeEvents:[...input.activeEvents,{id:`active-${event.id}-${input.clock.turn}-${input.rngSeed}`,definitionId:event.id,name:event.name,kind:event.kind,startedTurn:input.clock.turn,remainingTurns:event.durationTurns,perTurnDelta:event.perTurnDelta,manualEndItemIds:event.manualEndItemIds,responses:event.responses,followUp:"followUp" in event?event.followUp:undefined,source}]};}

function resolveActiveEvents(input:GameState):GameState{let state=input;let endedBad=false;const keep:GameState["activeEvents"]=[];const followUps:Array<{event:EventFollowUp;source:string}>=[];for(const active of state.activeEvents){if(active.startedTurn>=state.clock.turn){keep.push(active);continue;}state=withStats(state,active.perTurnDelta);const remainingTurns=active.remainingTurns-1;state=publicFact(state,{category:"事件",title:`${active.name}仍在持续`,text:`本轮影响已结算，剩余 ${Math.max(0,remainingTurns)} 轮；${active.manualEndItemIds.length?`${state.playerName}可用指定道具提前处理`:"可以选择不同应对方式"}。`,deltas:active.perTurnDelta});if(remainingTurns>0)keep.push({...active,remainingTurns});else{endedBad ||= active.kind==="accident"||active.kind==="sickness";state=publicFact(state,{category:"状态",title:`${active.name}自然结束`,text:"持续影响已经停止。"});if(active.followUp){let roll;[roll,state]=random(state);if(roll<active.followUp.chance)followUps.push({event:active.followUp,source:active.source});}}}state={...state,activeEvents:keep};for(const item of followUps){state=withStats(state,item.event.statDelta);state=activateEvent(state,item.event,item.source);if(item.event.kind==="accident")state={...state,condition:"轻伤"};if(item.event.kind==="sickness")state={...state,condition:"生病"};state=publicFact(state,{category:"事件",title:`后续事件 · ${item.event.name}`,text:`${item.event.text} ${state.playerName}可以在下一轮选择应对。`,deltas:item.event.statDelta});}const stillUnwell=state.activeEvents.some(active=>active.kind==="accident"||active.kind==="sickness");return {...state,condition:endedBad&&!stillUnwell?"健康":state.condition};}

function resolveRouteEvent(input:GameState,routeId:string):GameState{let state=input;const chance=(ROUTE_EVENT_TRIGGER_CHANCES[routeId]?.[state.clock.period==="昼"?"day":"night"]??0)*(state.activeEvents.length?.65:1);let trigger;[trigger,state]=random(state);if(trigger>=chance)return state;const weighted=ROUTE_EVENT_TABLE.map(event=>({event,weight:event.weight*((state.recentEventIds??[]).slice(0,4).includes(event.id)?.18:1)}));let pick;[pick,state]=random(state);let cursor=pick*weighted.reduce((sum,item)=>sum+item.weight,0);const chosen=weighted.find(item=>(cursor-=item.weight)<=0)?.event??ROUTE_EVENT_TABLE[0];state=withStats(state,chosen.statDelta);state=activateEvent(state,chosen,`路线 ${routeId}`);return publicFact(state,{category:"事件",title:`路途中 · ${chosen.name}`,text:`${chosen.text} 持续 ${chosen.durationTurns} 轮；${state.playerName}可选择应对${chosen.manualEndItemIds.length?`，也可用 ${chosen.manualEndItemIds.join("/")} 提前结束`:""}。`,deltas:chosen.statDelta,moneyDelta:chosen.moneyDelta||undefined});}

function resolveDelayed(input:GameState):GameState{let state=input;const due=state.delayedEffects.filter(e=>e.dueTurn<=state.clock.turn).sort((a,b)=>a.dueTurn-b.dueTurn);state={...state,delayedEffects:state.delayedEffects.filter(e=>e.dueTurn>state.clock.turn)};for(const effect of due){if(effect.kind==="travel_injury"){state={...withStats(state,{health:-16,energy:-8,mood:-5}),condition:"轻伤",plan:{id:`recovery-${state.clock.turn}`,kind:"recovery",goal:"处理旅途轻伤",createdAt:state.now,steps:[{id:"diagnose",label:"确认伤势",status:"待办"},{id:"care",label:"治疗或就医",status:"待办"},{id:"recover",label:"完成恢复",status:"待办"}]}};state=publicFact(state,{category:"事件",title:"旅途中出现小意外",text:`伤势可以恢复；${state.playerName}下轮会根据物资和预算重新安排。`,deltas:{health:-16,energy:-8,mood:-5}});}if(effect.kind==="trip_return"){const target=effect.source as PlaceId;state={...state,positionId:target,currentRouteId:null,plan:state.condition==="健康"?null:state.plan,visitedPlaces:Array.from(new Set([...state.visitedPlaces,target]))};state=publicFact(withStats(state,{experience:6,mood:4}),{category:"旅行",title:`抵达${getPlace(target).name}`,text:"路线结果已经揭晓，接下来按当地概率表结算探索。",deltas:{experience:6,mood:4}});}if(effect.kind==="recovery_complete"){state={...withStats(state,{health:18,energy:8}),condition:"健康",plan:null};state=publicFact(state,{category:"状态",title:"恢复健康",text:`${effect.source}后的恢复期结束。`,deltas:{health:18,energy:8}});}}return state;}

function resolvePlaceEvent(input:GameState,triggerMultiplier=1):GameState{
  const positionId=input.positionId;if(!positionId||input.currentRouteId)return input;
  let state=input;const place=getPlace(positionId);
  const baseTrigger=PLACE_EVENT_TRIGGER_CHANCES[place.id][state.clock.period==="昼"?"day":"night"];
  const triggerChance=Math.min(.95,baseTrigger*(state.activeEvents.length?.6:1)*triggerMultiplier);
  let trigger;[trigger,state]=random(state);if(trigger>=triggerChance)return state;
  const adjusted=place.eventTable.map(event=>{let weight=event.weight;if(event.kind==="discovery")weight*=.55+state.stats.mood/100;if(event.kind==="accident")weight*=state.stats.health<55?1.7:1;if(event.kind==="sickness"&&["雨","雪","暴风雨"].includes(state.weather))weight*=1.8;if((state.recentEventIds??[]).slice(0,4).includes(event.id))weight*=.18;return {event,weight};});
  const total=adjusted.reduce((sum,item)=>sum+item.weight,0);let roll;[roll,state]=random(state);let cursor=roll*total;const chosen=adjusted.find(item=>(cursor-=item.weight)<=0)?.event??adjusted.at(-1)!.event;
  let cash,exp,mood;[cash,state]=randomInt(state,place.numericYield.money);[exp,state]=randomInt(state,place.numericYield.experience);[mood,state]=randomInt(state,place.numericYield.mood);cash+=chosen.moneyDelta;
  state=withStats(state,{...chosen.statDelta,experience:(chosen.statDelta.experience??0)+exp,mood:(chosen.statDelta.mood??0)+mood});state=activateEvent(state,chosen,place.name);
  if(cash!==0){state={...state,money:Math.max(0,state.money+cash)};state=ledger(state,"探索",cash,`${place.name}：${chosen.name}`);}
  let dropRoll;[dropRoll,state]=random(state);const moodFactor=.55+state.stats.mood/100;let dropText="没有额外道具";
  if(dropRoll<Math.min(.9,place.numericYield.baseItemChance*moodFactor)){let pick;[pick,state]=random(state);let itemCursor=pick*place.itemPool.reduce((sum,item)=>sum+item.weight,0);const item=place.itemPool.find(candidate=>(itemCursor-=candidate.weight)<=0)??place.itemPool[0];state=collectPlaceDrop(state,item,place.id);const itemName=personalize(item.interaction?.titleTemplate??item.name,state);dropText=item.interaction?`收到了${itemName}，已放进私藏信件`:`获得${itemName}（${item.uses}次）`;}
  if(chosen.kind==="accident")state={...state,condition:"轻伤"};if(chosen.kind==="sickness")state={...state,condition:"生病"};
  const ending=`持续 ${chosen.durationTurns} 轮；${state.playerName}有 ${chosen.responses.length} 种普通应对${chosen.manualEndItemIds.length?`，也可用 ${chosen.manualEndItemIds.join("/")} 提前结束`:""}`;
  return publicFact(state,{category:"事件",title:`${place.name} · ${chosen.name}`,text:`${chosen.text} 数字收益：金币 ${cash>=0?"+":""}${cash}、成长 +${exp}、心情 +${mood}；${dropText}；${ending}。`,moneyDelta:cash,deltas:{...chosen.statDelta,experience:exp,mood}});
}

function progressJourney(input:GameState):GameState{
  const journey=input.activeJourney;if(!journey)return input;
  let state=input;const route=getRoute(journey.routeId);const destination=getPlace(journey.destinationId);
  if(journey.stage==="outbound"){
    state=withStats(state,{energy:-4,satiety:-3,experience:1});state=resolveRouteEvent(state,route.id);
    const remainingTurns=journey.remainingTurns-1;state=appendJourneyMoment(state,{turn:state.clock.turn,stage:"outbound",title:`去程路段`,text:`完成一段路程，还有 ${Math.max(0,remainingTurns)} 轮到达。`});
    state={...state,activeJourney:{...state.activeJourney!,stage:remainingTurns<=0?"play":"outbound",remainingTurns:remainingTurns<=0?1:remainingTurns}};
    return publicFact(state,{category:"旅行",title:remainingTurns<=0?`抵达${destination.name}`:"去程继续",text:remainingTurns<=0?"今轮只用于完成路程，下轮才开始游玩。":`每段路程消耗一轮，还剩 ${remainingTurns} 轮。`,deltas:{energy:-4,satiety:-3,experience:1}});
  }
  if(journey.stage==="play"){
    state=withStats(state,{energy:-7,satiety:-4,activity:4,experience:2});
    state={...state,positionId:journey.destinationId,currentRouteId:null,visitedPlaces:Array.from(new Set([...state.visitedPlaces,journey.destinationId]))};
    state=resolvePlaceEvent(state,1.2);state={...state,positionId:null,currentRouteId:route.id};
    if(journey.pendingContinue){const nextRoute=getRoute(journey.pendingContinue.routeId);const next=journey.pendingContinue.destinationId;state=appendJourneyMoment(state,{turn:state.clock.turn,stage:"outbound",title:`转场：出发去${getPlace(next).name}`,text:`在${destination.name}游玩后直接转场，不回家。`});state={...state,activeJourney:{...state.activeJourney!,stage:"outbound",routeId:nextRoute.id,destinationId:next,remainingTurns:nextRoute.travelTurns,overnightCount:journey.overnightCount,incidentRiskMultiplier:1,pendingContinue:null}};return publicFact(state,{category:"旅行",title:`续行前往${getPlace(next).name}`,text:`已从${destination.name}转场出发，途中照常结算路线事件。`});}
    let roll;[roll,state]=random(state);const overnightChance=state.stats.energy>=65?Math.min(.55,.16+(state.stats.energy-65)*.015):0;const stays=roll<overnightChance;
    state=appendJourneyMoment(state,{turn:state.clock.turn,stage:"play",title:`在${destination.name}游玩`,text:stays?"精力还很充足，今夜没有返家。":"游玩结束，开始安排返程。"});
    state={...state,activeJourney:{...state.activeJourney!,stage:stays?"overnight":"return",remainingTurns:stays?1:route.travelTurns,incidentRiskMultiplier:stays?1.35:1}};
    return publicFact(state,{category:"旅行",title:stays?"今夜没有回家":"游玩结束",text:stays?`当前精力允许留宿；意外触发率提高至平时的 1.35 倍。`:`在${destination.name}完成一轮游玩，下轮进入返程。`,deltas:{energy:-7,satiety:-4,activity:4,experience:2}});
  }
  if(journey.stage==="overnight"){
    const count=journey.overnightCount+1;state=withStats(state,{energy:-7,satiety:-5,mood:2});let incident;[incident,state]=random(state);const incidentChance=Math.min(.72,route.risk*.65*journey.incidentRiskMultiplier);
    let incidentText="平安留宿了一轮。";
    if(incident<incidentChance){state={...withStats(state,{health:-8,energy:-4,mood:-2}),condition:"轻伤"};incidentText="夜间遇到了可恢复的小意外。";state=publicFact(state,{category:"事件",title:"夜不归宿的小意外",text:`留宿轮次提高了风险；伤势不会导致永久失败，回家后${state.playerName}会安排恢复。`,deltas:{health:-8,energy:-4,mood:-2}});}
    let stayRoll;[stayRoll,state]=random(state);const staysAgain=count<2&&state.stats.energy>=70&&stayRoll<.22;
    state=appendJourneyMoment(state,{turn:state.clock.turn,stage:"overnight",title:`外宿第 ${count} 轮`,text:`${incidentText}${staysAgain?"精力允许再留一轮。":"已决定返家。"}`});
    state={...state,activeJourney:{...state.activeJourney!,stage:staysAgain?"overnight":"return",remainingTurns:staysAgain?1:route.travelTurns,overnightCount:count,incidentRiskMultiplier:1+(count+1)*.35}};
    return publicFact(state,{category:"旅行",title:`外宿第 ${count} 轮结束`,text:incidentText,deltas:{energy:-7,satiety:-5,mood:2}});
  }
  state=withStats(state,{energy:-4,satiety:-3,experience:1});state=resolveRouteEvent(state,route.id);const remainingTurns=journey.remainingTurns-1;
  const returnMoment:TravelMoment={turn:state.clock.turn,stage:"return",title:remainingTurns<=0?"回到小窝":"返程路段",text:remainingTurns<=0?"这次出游正式结束。":`还有 ${remainingTurns} 轮到家。`};const moments=[...state.activeJourney!.moments,returnMoment];
  if(remainingTurns>0){state={...state,activeJourney:{...state.activeJourney!,remainingTurns,moments}};return publicFact(state,{category:"旅行",title:"返程继续",text:`还剩 ${remainingTurns} 段路程，宠物仍不在小窝。`,deltas:{energy:-4,satiety:-3,experience:1}});}
  // 每次转场恰好产生一条“续行前往…”决策记录，按它计数，避免与“转场：出发去…”重复统计
const transferCount=moments.filter(m=>m.title.startsWith("续行前往")).length;
  const agentSummary=`我安排了 ${moments.length} 条行程记录${transferCount?`，含 ${transferCount} 次途中转场`:""}${journey.overnightCount?`，经历 ${journey.overnightCount} 轮外宿`:""}；下次会继续根据健康、精力和预算调整距离。`;
  state={...state,positionId:state.homeId,currentRouteId:null,activeJourney:null,plan:state.condition==="健康"?null:{id:`recovery-${state.clock.turn}`,kind:"recovery",goal:"回家后恢复健康",createdAt:state.now,steps:[{id:"diagnose",label:"确认状况",status:"待办"},{id:"care",label:"治疗或就医",status:"待办"},{id:"recover",label:"完成恢复",status:"待办"}]},travelChronicles:[{id:journey.id,destinationId:journey.destinationId,startedTurn:journey.startedTurn,endedTurn:state.clock.turn,title:`${destination.name}出游小记`,summary:`第 ${journey.startedTurn}–${state.clock.turn} 轮，去程、游玩${transferCount?`、${transferCount} 次转场`:""}${journey.overnightCount?`、外宿 ${journey.overnightCount} 轮`:""}、返程已全部完成。`,agentSummary,moments,comments:[]},...state.travelChronicles].slice(0,30)};
  return publicFact(withStats(state,{mood:4,experience:4}),{category:"旅行",title:"已回到小窝",text:`${destination.name}出游结束，旅途小记已归档。`,deltas:{mood:4,experience:4}});
}

export function startNextSession(input:GameState,now=Date.now()):GameState{
  const nextClock=clockFor(input.clock.turn+1);const settled=input.pendingActions.map(queued=>({id:queued.id,turn:nextClock.turn,actionLabel:queued.option.label,reasonCode:queued.decision.reasonCode,note:queued.decision.note,cost:queued.option.cost}));let state:GameState={...input,now,clock:nextClock,season:seasonFor(nextClock.month),weather:weatherFor(input.rngSeed,nextClock.turn,input.positionId??input.activeJourney?.destinationId??input.homeId??"station"),previousStats:input.stats,pendingActions:[],lastSettledDecisions:settled};
  state=withStats(state,{energy:-5,satiety:-7,activity:-2,health:input.stats.satiety<18?-4:0});
  for(const queued of input.pendingActions)state=settleQueuedAction(state,queued);
  state=resolveActiveEvents(state);const planBeforeDelayed=state.plan;state=resolveDelayed(state);if(planBeforeDelayed?.kind==="trip"&&!state.plan&&state.condition==="健康"&&state.positionId)state={...state,plan:planBeforeDelayed};
  if(state.activeJourney)state=progressJourney(state);else state=resolvePlaceEvent(state);
  if(state.homeId){
    const homeId=state.homeId;const place=getPlace(homeId);
    const healthBonus=state.stats.health===100?4:state.stats.health>=95?2:0;const base=Math.round(8*place.incomeMultiplier);const gross=base+healthBonus;const repay=Math.min(state.debt,Math.floor(gross*.25));
    state={...state,money:state.money+gross-repay,debt:state.debt-repay};state=ledger(state,"收入",gross-repay,repay?`第 ${nextClock.turn} 轮收入（偿还 ${repay}）`:`第 ${nextClock.turn} 轮保底收入（${place.name} 倍率 ${place.incomeMultiplier}，健康奖励 ${healthBonus}）`);state=publicFact(state,{category:"费用",title:"本轮收入到账",text:`保底 8 × ${place.name} 收入倍率 ${place.incomeMultiplier} = ${base}，健康奖励 ${healthBonus}；健康不足时仍保留基础照料资金。`,moneyDelta:gross-repay});
    if(nextClock.period==="夜")state={...state,shopCycle:state.shopCycle+1,shop:createShop(homeId,state.shopCycle+1,state.rngSeed)};
  }
  return publicFact(state,{category:"系统",title:`第 ${nextClock.turn} 轮上线`,text:`第 ${nextClock.day} 天·${nextClock.period}，第 ${nextClock.month} 月；上一轮的安排、取舍与隐藏后果已全部揭晓。`});
}

export function settleTime(input:GameState,targetNow=Date.now()):GameState{return {...input,now:targetNow};}
export function triggerRecoverableAccident(state:GameState,dueTurn=state.clock.turn+1):GameState{return {...state,delayedEffects:[...state.delayedEffects,{id:`debug-${state.clock.turn}`,dueTurn,kind:"travel_injury",severity:1,source:"测试路线"}]};}
export function setMoodSignal(state:GameState,mood:Mood):GameState{return {...state,moodSignal:mood};}
export function submitWish(state:GameState,text:string,at=Date.now()):GameState{return {...state,wish:{id:`wish-${at}`,text:text.slice(0,120),createdAt:at,considered:false}};}
export function addTravelComment(state:GameState,chronicleId:string,text:string,at=Date.now()):GameState{const clean=text.trim().slice(0,180);if(!clean)return state;return {...state,travelChronicles:state.travelChronicles.map(entry=>entry.id===chronicleId?{...entry,comments:[...entry.comments,{id:`comment-${at}`,at,text:clean}]}:entry)};}
export function appendCaretakerEntry(state:GameState,changes:Omit<JournalRevision,"at"|"turn">):GameState{const revision:JournalRevision={...changes,at:state.now,turn:state.clock.turn};return {...state,caretakerJournal:[{id:`care-agent-${state.clock.turn}-${state.caretakerJournal.length}`,createdAt:state.now,revisions:[revision]},...state.caretakerJournal].slice(0,100)};}
export function updateTravelSummary(state:GameState,chronicleId:string,summary:string):GameState{return {...state,travelChronicles:state.travelChronicles.map(entry=>entry.id===chronicleId?{...entry,agentSummary:summary.trim().slice(0,360)||entry.agentSummary}:entry)};}
export function getWorldContract(state:GameState){return {places:PLACES,routes:state.positionId?routesFrom(state.positionId):[],season:state.season,weather:state.weather,currentPlace:state.positionId?getPlace(state.positionId):null,placeEventTriggerChances:PLACE_EVENT_TRIGGER_CHANCES,routeEventTriggerChances:ROUTE_EVENT_TRIGGER_CHANCES,routeEventTable:ROUTE_EVENT_TABLE} as const;}
export function getDecisionContext(state:GameState){return {state,legalActions:getLegalActions(state),latestWish:state.wish,recentPublicFacts:state.publicLog.slice(0,10),privateJournal:state.caretakerJournal.slice(0,10),world:getWorldContract(state),rules:RULE_CONTRACT};}
