import assert from "node:assert/strict";
import test from "node:test";
import { ExampleAgentPolicy } from "./caretaker";
import { addTravelComment, collectPlaceDrop, configureIdentity, createInitialState, getDecisionContext, getLegalActions, migrateState, queueAction, startNextSession, submitWish, triggerRecoverableAccident } from "./engine";
import type { Decision, GameState } from "./model";
import { createShop, PLACE_EVENT_TRIGGER_CHANCES, PLACES, ROUTE_EVENT_TABLE, ROUTE_EVENT_TRIGGER_CHANCES, ROUTES } from "./world";

const caretaker=new ExampleAgentPolicy();
const decision=(actionKey:string):Decision=>({actionKey,reasonCode:"explore",note:"测试安排",continueSession:false});
async function aiStep(state:GameState){const context=getDecisionContext(state);const picked=await caretaker.decide(context);return {decision:picked,state:queueAction(state,picked)};}

test("AI 先安排住址，下轮才扣款并揭晓",async()=>{const initial=createInitialState(1_000_000);const planned=await aiStep(initial);assert.equal(planned.decision.actionKey,"choose_home:station");assert.equal(planned.state.homeId,null);assert.equal(planned.state.money,100);assert.equal(planned.state.pendingActions.length,1);const revealed=startNextSession(planned.state,1_000_001);assert.equal(revealed.homeId,"station");assert.ok(revealed.ledger.some(e=>e.category==="住房"));});

test("每个地点都有事件持续规则、AI 多解应对、昼夜触发率、数字收益和道具次数",()=>{for(const place of PLACES){assert.equal(place.eventTable.reduce((sum,e)=>sum+e.weight,0),100);assert.ok(place.eventTable.every(event=>event.durationTurns>0&&event.perTurnDelta&&event.manualEndItemIds&&event.responses.length>=2));assert.ok(PLACE_EVENT_TRIGGER_CHANCES[place.id].day>0&&PLACE_EVENT_TRIGGER_CHANCES[place.id].night>0);assert.ok(place.numericYield.baseItemChance>0);assert.ok(place.itemPool.every(item=>item.uses>0));}assert.ok(PLACES.flatMap(place=>place.eventTable).filter(event=>event.followUp).length>=6);});

test("每条路线都有昼夜事件触发率、应对选项且路线事件权重为 100",()=>{assert.equal(ROUTE_EVENT_TABLE.reduce((sum,event)=>sum+event.weight,0),100);assert.ok(ROUTE_EVENT_TABLE.every(event=>event.responses.length>=2));assert.ok(ROUTE_EVENT_TABLE.filter(event=>event.followUp).length>=2);for(const route of ROUTES){assert.ok(ROUTE_EVENT_TRIGGER_CHANCES[route.id].day>0);assert.ok(ROUTE_EVENT_TRIGGER_CHANCES[route.id].night>0);}});

test("商店按地点和日轮确定性轮换",()=>{assert.deepEqual(createShop("station",3,9),createShop("station",3,9));assert.notDeepEqual(createShop("station",3,9),createShop("city",3,9));let state=createInitialState(1);state=queueAction(state,decision("choose_home:station"));state=startNextSession(state,2);assert.equal(state.clock.period,"夜");assert.equal(state.shopCycle,1);assert.ok(state.shop.every(item=>item.uses>0));});

test("成长限制远行，成长提升后开放更远路线",()=>{let state=createInitialState(1);state={...state,homeId:"station",positionId:"station",shop:createShop("station",0,1),stats:{...state.stats,experience:10}};assert.equal(getLegalActions(state).some(a=>a.key==="plan_trip:station-lake"),false);state={...state,stats:{...state.stats,experience:20}};assert.equal(getLegalActions(state).some(a=>a.key==="plan_trip:station-lake"),true);assert.equal(getLegalActions(state).some(a=>a.key==="plan_trip:station-coast"),false);state={...state,stats:{...state.stats,experience:30}};assert.equal(getLegalActions(state).some(a=>a.key==="plan_trip:station-coast"),true);});

test("临界饱腹和精力由程序强制优先照料，不把风险选择交给模型",()=>{let state=createInitialState(1);state={...state,homeId:"station",positionId:"station",money:80,shop:createShop("station",0,1),stats:{...state.stats,satiety:12,energy:18,experience:40},activeEvents:[{id:"urgent-event",definitionId:"station-task",name:"临时委托",kind:"opportunity",startedTurn:1,remainingTurns:2,perTurnDelta:{energy:-1},manualEndItemIds:[],responses:PLACES[2].eventTable.find(event=>event.id==="station-task")!.responses,source:"测试"}]};const legal=getLegalActions(state);assert.ok(legal.length>0);assert.ok(legal.every(action=>action.actionId==="feed"||(action.actionId==="buy"&&["snack","meal"].includes(action.itemId??""))));assert.equal(legal.some(action=>action.actionId==="respond_event"),false);state={...state,stats:{...state.stats,satiety:60,energy:60},plan:{id:"trip",kind:"trip",goal:"测试",createdAt:1,targetPlaceId:"lake",routeId:"station-lake",steps:[{id:"budget",label:"预算",status:"完成"},{id:"supplies",label:"用品",status:"完成"},{id:"health",label:"检查",status:"完成"},{id:"depart",label:"出发",status:"待办"}]},inventory:[{id:"trip-kit",name:"旅行用品包",kind:"resource",usesRemaining:2,maxUses:2}],activeEvents:[]};assert.ok(getLegalActions(state).some(action=>action.actionId==="depart_trip"));state={...state,stats:{...state.stats,satiety:30}};assert.equal(getLegalActions(state).some(action=>action.actionId==="depart_trip"),false);});

test("营养便当和地点食物可直接喂食，旅行途中也不会被动作过滤",()=>{let state=createInitialState(1);state={...state,homeId:"hill",positionId:null,currentRouteId:"hill-station",stats:{...state.stats,satiety:15,energy:70},inventory:[{id:"meal",name:"营养便当",kind:"food",usesRemaining:2,maxUses:2},{id:"wild-berry",name:"山野果",kind:"food",usesRemaining:1,maxUses:1}],activeJourney:{id:"journey-food",routeId:"hill-station",destinationId:"station",startedTurn:1,stage:"return",remainingTurns:2,overnightCount:0,incidentRiskMultiplier:1,moments:[]}};const legal=getLegalActions(state);assert.ok(legal.some(action=>action.key==="feed:meal"));assert.ok(legal.some(action=>action.key==="feed:wild-berry"));state=queueAction(state,decision("feed:meal"));assert.equal(getLegalActions(state).some(action=>action.key==="feed:meal"),false);state=startNextSession(state,2);assert.equal(state.inventory.find(item=>item.id==="meal")?.usesRemaining,1);assert.ok(state.stats.satiety>15);assert.ok(state.activeJourney?.moments.some(moment=>moment.title.includes("准备营养便当")));});

test("旅行经历去程、游玩、可选外宿和返程，回家后才归档",()=>{let state=createInitialState(1);const stable=(s:GameState):GameState=>({...s,condition:"健康",activeEvents:[],stats:{...s.stats,health:80,energy:80,experience:30}});state={...state,homeId:"station",positionId:"station",money:120,shop:createShop("station",0,1),stats:{...state.stats,experience:30}};state=submitWish(state,"想去湖边旅行",2);state=queueAction(state,decision("plan_trip:station-lake"));assert.equal(state.plan,null);state=stable(startNextSession(state,3));assert.equal(state.plan?.kind,"trip");state=queueAction(state,decision("buy:trip-kit"));state=stable(startNextSession(state,4));assert.ok(state.inventory.some(i=>i.id==="trip-kit"&&i.usesRemaining>0));state=queueAction(state,decision("check_health"));state=stable(startNextSession(state,5));assert.ok(getLegalActions(state).some(a=>a.key==="depart_trip:station-lake"));state=queueAction(state,decision("depart_trip:station-lake"));assert.equal(state.positionId,"station");state=startNextSession(state,6);assert.ok(state.activeJourney);assert.equal(state.positionId,null);assert.ok(state.ledger.some(e=>e.category==="旅行"));for(let turn=7;state.activeJourney&&turn<16;turn++)state=startNextSession(state,turn);assert.equal(state.activeJourney,null);assert.equal(state.positionId,"station");assert.ok(state.visitedPlaces.includes("lake"));assert.equal(state.travelChronicles.length,1);assert.ok(state.travelChronicles[0].moments.some(moment=>moment.stage==="play"));assert.equal(state.travelChronicles[0].moments.at(-1)?.stage,"return");});

test("高精力可触发夜不归宿，外宿会累加意外风险",()=>{let found:GameState|null=null;for(let seed=1;seed<80&&!found;seed++){let state=createInitialState(1);state={...state,homeId:"station",positionId:null,currentRouteId:"station-lake",rngSeed:seed,stats:{...state.stats,health:100,energy:100,experience:30},activeJourney:{id:`night-${seed}`,routeId:"station-lake",destinationId:"lake",startedTurn:1,stage:"play",remainingTurns:1,overnightCount:0,incidentRiskMultiplier:1,moments:[]}};state=startNextSession(state,2);if(state.activeJourney?.stage==="overnight")found=state;}assert.ok(found?.activeJourney);const before=found!.activeJourney!.incidentRiskMultiplier;const after=startNextSession(found!,3);assert.ok((after.activeJourney?.incidentRiskMultiplier??before)>before||after.travelChronicles.length>0);assert.ok((after.activeJourney?.moments??after.travelChronicles[0]?.moments??[]).some(moment=>moment.stage==="overnight"));});

test("每轮保底收入按健康奖励，旅途小记接受 user 留言",()=>{let perfect=createInitialState(1);perfect={...perfect,homeId:"station",positionId:null,money:0,stats:{...perfect.stats,health:100}};perfect=startNextSession(perfect,2);assert.equal(perfect.ledger.find(entry=>entry.category==="收入")?.amount,12);let lower=createInitialState(1);lower={...lower,homeId:"station",positionId:null,money:0,stats:{...lower.stats,health:94}};lower=startNextSession(lower,2);assert.equal(lower.ledger.find(entry=>entry.category==="收入")?.amount,8);const chronicle={id:"trip-note",destinationId:"lake" as const,startedTurn:1,endedTurn:4,title:"测试小记",summary:"完成",agentSummary:"下次调整。",moments:[],comments:[]};lower={...lower,travelChronicles:[chronicle]};lower=addTravelComment(lower,"trip-note","下次记得带雨衣",9);assert.equal(lower.travelChronicles[0].comments[0].text,"下次记得带雨衣");});

test("道具按实际生效次数消耗且意外可恢复",()=>{let state=createInitialState(1);state={...state,homeId:"hill",positionId:null,shop:createShop("hill",0,1),inventory:[{id:"bandage",name:"应急绷带",kind:"medicine",usesRemaining:2,maxUses:2}]};state=triggerRecoverableAccident(state);state=startNextSession(state,2);assert.equal(state.condition,"轻伤");state=queueAction(state,decision("diagnose"));state=startNextSession(state,3);state=queueAction(state,decision("treat"));state=startNextSession(state,4);assert.equal(state.inventory.find(i=>i.id==="bandage")?.usesRemaining,1);assert.equal(state.condition,"恢复中");state=startNextSession(state,5);assert.equal(state.condition,"健康");});

test("旧的恢复完成后果不会误删新建立的旅行计划",()=>{let state=createInitialState(1);state={...state,homeId:"station",positionId:"station",condition:"恢复中",delayedEffects:[{id:"old-recovery",dueTurn:2,kind:"recovery_complete",severity:0,source:"旧恢复"}],plan:{id:"new-trip",kind:"trip",goal:"前往月湖木屋",targetPlaceId:"lake",createdAt:1,steps:[{id:"save",label:"预算",status:"完成"},{id:"supplies",label:"用品",status:"待办"},{id:"health",label:"检查",status:"待办"},{id:"depart",label:"出发",status:"待办"}]}};state=startNextSession(state,2);assert.equal(state.condition,"健康");assert.equal(state.plan?.kind,"trip");});

test("持续事件每轮生效，AI 可消耗指定道具提前结束",()=>{let state=createInitialState(1);const template=PLACES[0].eventTable.find(event=>event.kind==="accident")!;state={...state,homeId:"hill",positionId:"hill",condition:"轻伤",inventory:[{id:"bandage",name:"应急绷带",kind:"medicine",usesRemaining:2,maxUses:2}],activeEvents:[{id:"active-test",definitionId:"test-injury",name:"轻伤",kind:"accident",startedTurn:1,remainingTurns:3,perTurnDelta:{health:-3,activity:-2},manualEndItemIds:["bandage"],responses:template.responses,source:"测试"}]};const action=getLegalActions(state).find(a=>a.actionId==="resolve_event");assert.ok(action);state=queueAction(state,decision(action!.key));const health=state.stats.health;state=startNextSession(state,2);assert.equal(state.activeEvents.some(event=>event.id==="active-test"),false);assert.equal(state.inventory.find(i=>i.id==="bandage")?.usesRemaining,1);assert.ok(state.stats.health>=health-3);});

test("AI 可在不消耗道具时权衡事件应对，选择在下轮结算",()=>{let state=createInitialState(1);const template=PLACES[1].eventTable.find(event=>event.kind==="opportunity")!;state={...state,homeId:"hill",positionId:null,activeEvents:[{id:"choice-test",definitionId:template.id,name:template.name,kind:template.kind,startedTurn:1,remainingTurns:2,perTurnDelta:template.perTurnDelta,manualEndItemIds:[],responses:template.responses,source:"测试"}]};const choices=getLegalActions(state).filter(action=>action.actionId==="respond_event");assert.equal(choices.length,2);state=queueAction(state,decision(choices.find(action=>action.eventResponseId==="steady")!.key));state=startNextSession(state,2);assert.ok(state.publicLog.some(entry=>entry.title.includes("饲养者应对了")));assert.equal(state.activeEvents.some(event=>event.id==="choice-test"),false);});

test("持续事件自然结束后可确定性触发后续事件链",()=>{let state=createInitialState(1);const template=PLACES[4].eventTable.find(event=>event.followUp)!;const followUp={...template.followUp!,chance:1};state={...state,homeId:"lake",positionId:null,activeEvents:[{id:"chain-test",definitionId:template.id,name:template.name,kind:template.kind,startedTurn:1,remainingTurns:1,perTurnDelta:{},manualEndItemIds:[],responses:template.responses,followUp,source:"月湖木屋"}]};state=startNextSession(state,2);assert.ok(state.activeEvents.some(event=>event.definitionId===followUp.id));assert.ok(state.publicLog.some(entry=>entry.title===`后续事件 · ${followUp.name}`));assert.ok(state.recentEventIds.includes(followUp.id));});

test("私人安排不污染公开事实，刷新本身不推进轮次",()=>{let state=createInitialState(1);const publicCount=state.publicLog.length;state=queueAction(state,{...decision("choose_home:station"),reasonCode:"settle",note:"交通与医疗更均衡"});assert.equal(state.publicLog.length,publicCount);assert.equal(state.caretakerJournal[0].revisions[0].hypothesis,"安顿与建立基础");const migrated=migrateState(JSON.parse(JSON.stringify(state)),999);assert.equal(migrated.clock.turn,1);assert.equal(migrated.pendingActions.length,1);});

test("agent 只提交紧凑决策，程序自动生成日记与上线决策摘要",()=>{let state=createInitialState(1);state=queueAction(state,{actionKey:"choose_home:station",reasonCode:"settle",note:"交通均衡",continueSession:false});assert.equal(Object.keys(state.pendingActions[0].decision).some(key=>["observation","hypothesis","narration"].includes(key)),false);assert.match(state.caretakerJournal[0].revisions[0].observation,/健康/);state=startNextSession(state,2);assert.equal(state.lastSettledDecisions[0].reasonCode,"settle");assert.equal(state.lastSettledDecisions[0].note,"交通均衡");});

test("每轮保留结算前数值，前端可精确显示宠物变化",()=>{let state=createInitialState(1);const before={...state.stats};state=queueAction(state,decision("choose_home:station"));state=startNextSession(state,2);assert.deepEqual(state.previousStats,before);assert.notDeepEqual(state.stats,state.previousStats);const migrated=migrateState(JSON.parse(JSON.stringify(state)),3);assert.deepEqual(migrated.previousStats,before);});

test("2轮一天、10天一月，非法或过期动作不会占用资源",()=>{let state=createInitialState(1);for(let i=0;i<19;i++)state=startNextSession(state,i+2);assert.equal(state.clock.turn,20);assert.equal(state.clock.day,10);assert.equal(state.clock.month,1);state=startNextSession(state,30);assert.equal(state.clock.turn,21);assert.equal(state.clock.day,11);assert.equal(state.clock.month,2);const money=state.money;state=queueAction(state,decision("depart_trip:station-lake"));assert.equal(state.money,money);assert.equal(state.pendingActions.length,0);});

test("长期存档的公开日志编号会被稳定去重",()=>{const state=createInitialState(1);const duplicate={...state.publicLog[0],id:"same"};const migrated=migrateState({...state,publicLog:[duplicate,duplicate,duplicate]},2);assert.equal(new Set(migrated.publicLog.map(entry=>entry.id)).size,3);assert.deepEqual(migrateState({...state,publicLog:[duplicate,duplicate,duplicate]},2).publicLog.map(entry=>entry.id),migrated.publicLog.map(entry=>entry.id));});

test("偏僻地点情书会带入双方名字并进入私藏，旧存档补齐新字段",()=>{let state=configureIdentity(createInitialState(1),{agentId:"local",playerName:"老公",petName:"乖乖"});const place=PLACES.find(item=>item.id==="moss-valley")!;const letter=place.itemPool.find(item=>item.interaction?.kind==="love-letter")!;state=collectPlaceDrop(state,letter,place.id);assert.equal(state.keepsakes.length,1);assert.match(state.keepsakes[0].name,/老公/);assert.match(state.keepsakes[0].body,/老公/);assert.match(state.keepsakes[0].body,/乖乖/);assert.equal(state.keepsakes[0].sourcePlaceName,"苔光谷");const old={...createInitialState(1),version:3 as const} as unknown as Record<string,unknown>;delete old.playerName;delete old.identityConfigured;delete old.keepsakes;const migrated=migrateState(old,2);assert.equal(migrated.playerName,"饲养者");assert.equal(migrated.identityConfigured,false);assert.deepEqual(migrated.keepsakes,[]);});
