"use client";

import { FormEvent, useEffect, useState } from "react";
import { createInitialState } from "../../core/engine";
import type { GameState, Mood } from "../../core/model";
import { getPlace, getRoute, PLACES, ROUTES } from "../../core/world";

const moods:Mood[]=["平静","开心","低落","焦虑","困倦"];
const stats={health:["健康","#db7663"],mood:["心情","#e49d52"],energy:["精力","#5f9294"],satiety:["饱腹","#b9845d"],activity:["活跃","#789269"],experience:["成长","#967faf"]} as const;
type View="room"|"map"|"trips"|"log"|"ledger"|"collection";
interface ObserverSnapshot { revision:number;session:{status:"online"|"offline";id:string|null;agentId:string|null;openedAt:number|null};state:GameState; }

export function GameApp(){
  const [state,setState]=useState<GameState>(()=>createInitialState());
  const [revision,setRevision]=useState(0);
  const [session,setSession]=useState<ObserverSnapshot["session"]>({status:"offline",id:null,agentId:null,openedAt:null});
  const [ready,setReady]=useState(false);
  const [busy,setBusy]=useState(false);
  const [wishText,setWishText]=useState("");
  const [view,setView]=useState<View>("room");
  const applySnapshot=(snapshot:ObserverSnapshot)=>{setState(snapshot.state);setRevision(snapshot.revision);setSession(snapshot.session);setReady(true)};
  const [connected,setConnected]=useState(true);
  const refresh=async()=>{try{const response=await fetch("/api/game",{cache:"no-store"});if(!response.ok)throw new Error(String(response.status));applySnapshot(await response.json() as ObserverSnapshot);setConnected(true);}catch{setConnected(false)}};
  useEffect(()=>{let alive=true;const boot=async()=>{try{const response=await fetch("/api/game",{cache:"no-store"});if(!response.ok)return;const snapshot=await response.json() as ObserverSnapshot;if(alive)applySnapshot(snapshot);setConnected(true);}catch{if(alive)setConnected(false)}};void boot();const timer=window.setInterval(()=>{if(alive)void refresh()},2000);return()=>{alive=false;clearInterval(timer)};// eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  const mutate=async(payload:Record<string,unknown>)=>{if(busy)return;setBusy(true);try{const response=await fetch("/api/game",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,type:"signal",requestId:crypto.randomUUID(),expectedRevision:revision})});if(response.ok){applySnapshot(await response.json() as ObserverSnapshot);setConnected(true);}else await refresh();}catch{setConnected(false)}finally{setBusy(false)}};
  const wish=(event:FormEvent)=>{event.preventDefault();if(!wishText.trim())return;void mutate({wish:wishText.trim()});setWishText("")};
  const commentTravel=(id:string,text:string)=>void mutate({chronicleId:id,comment:text});
  const latest=state.publicLog[0];
  const home=state.homeId?getPlace(state.homeId):null;
  return <main className="shell">
    <header className="topbar"><div><span className="eyebrow">第 {state.clock.month} 月 · 第 {state.clock.day} 天 · {state.clock.period} · {state.season}季</span><h1>小窝巡游</h1></div><div className="weather"><span>{state.weather} · {home?.name??"尚未安家"}</span><strong>◉ {state.money}</strong>{state.debt>0&&<em>待偿 {state.debt}</em>}</div></header>
    {!state.identityConfigured&&<div className="identityNotice"><b>等待第一次命名</b><span>玩家首次通过本地协议上线时，会给自己和小宠物取名。</span></div>}
    <PetStatusCard state={state}/>
    <nav className="viewTabs" aria-label="观察视图">{([['room','小窝·本轮'],['map','地图'],['trips','旅途小记'],['log','宠物日志'],['ledger','账本'],['collection','图鉴']] as [View,string][]).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav>
    <div className="layout">
      <section className="mainCard">
        {view==="room"&&<><Room state={state} thinking={session.status==="online"}/><DecisionBoard state={state}/><SessionRecap state={state}/></>} 
        {view==="map"&&<WorldMap state={state}/>} 
        {view==="trips"&&<TravelChronicles state={state} onComment={commentTravel}/>} 
        {view==="log"&&<PublicLog state={state} ready={ready}/>} 
        {view==="ledger"&&<Ledger state={state} ready={ready}/>} 
        {view==="collection"&&<Collection state={state}/>} 
        <div className="careRow"><div><span className="eyebrow">{state.pendingActions.length?`本轮已安排 ${state.pendingActions.length} 项 · 尚未结算`:"最近揭晓的事实"}</span><h2>{state.pendingActions.at(-1)?.option.label??latest.title}</h2><p>{state.pendingActions.length?`${state.playerName}下次上线时，系统才会统一揭晓后果。`:latest.text}</p></div><div className={`agentPresence ${session.status}`}><i/>{session.status==="online"?`${state.playerName} 在线`:`等待${state.playerName}上线`}<span>{session.status==="online"?"正在独立做决定":"系统不会代替玩家操作"}</span></div></div>
      </section>
      <aside className="side">
        <section className="panel"><div className="sectionTitle"><h2>给{state.playerName}一个信号</h2><span>不直接改变状态</span></div><p className="hint">{state.playerName}会读到{state.petName}的心情和愿望，最后由自己决定。</p><div className="moods">{moods.map(mood=><button disabled={busy} key={mood} className={state.moodSignal===mood?"selected":""} onClick={()=>void mutate({mood})}>{mood}</button>)}</div><form onSubmit={wish}><label htmlFor="wish">今天的小愿望</label><div className="wishInput"><input id="wish" value={wishText} onChange={e=>setWishText(e.target.value)} maxLength={120} placeholder="比如：想去看看湖……"/><button disabled={busy} aria-label="提交愿望">→</button></div></form>{state.wish&&<div className="wishNote"><b>愿望纸条</b><span>{state.wish.text}</span><em>{state.wish.considered?`${state.playerName}已纳入判断`:`等待${state.playerName}上线`}</em></div>}</section>
        <section className="panel planPanel"><div className="sectionTitle"><h2>{state.playerName}的安排</h2><span>{state.strategy.budgetStyle}</span></div>{state.plan?<><strong className="planGoal">{state.plan.goal}</strong><ol>{state.plan.steps.map(step=><li key={step.id} className={step.status==="完成"?"done":""}><i/>{step.label}<span>{step.status}</span></li>)}</ol></>:<p className="empty">当前没有多步计划，{state.playerName}下次上线时会重新判断。</p>}{state.activeEvents.length>0&&<div className="wishNote"><b>持续状态</b>{state.activeEvents.map(event=><span key={event.id}>{event.name} · 剩余 {event.remainingTurns} 轮</span>)}</div>}<div className="reserve">应急金目标 <b>{state.strategy.reserveTarget}</b></div></section>
        <section className="panel"><div className="sectionTitle"><h2>当地商店</h2><span>每个夜轮补货</span></div>{state.homeId?<div className="shopList">{state.shop.map(offer=><div key={offer.itemId}><span>{offer.name}<small>库存 {offer.stock} · {offer.uses} 次</small></span><b>◉ {offer.price}</b></div>)}</div>:<p className="empty">{state.playerName}选定住址后才会出现当地库存。</p>}<p className="hint bottom">采购只在本轮预订，下次上线才扣款入库。</p></section>
        <AgentConnection session={session} revision={revision} state={state}/>
        <section className="panel patrolPanel"><div className="sectionTitle"><h2>{state.playerName}的巡逻节奏</h2><label className="switch"><input aria-label="开启巡逻" type="checkbox" checked={state.patrolEnabled} onChange={e=>void mutate({patrolEnabled:e.target.checked})}/><i/></label></div><div className="periods">{[30,60,180,360].map(minutes=><button key={minutes} className={state.patrolMinutes===minutes?"selected":""} onClick={()=>void mutate({patrolMinutes:minutes})}>{minutes<60?`${minutes}分`:`${minutes/60}小时`}</button>)}</div><div className="reserve">建议唤醒周期 <b>{state.patrolEnabled?`${state.patrolMinutes}分钟`:"已暂停"}</b></div></section>
      </aside>
    </div>
    <footer><span>系统权威存档 · 事实日志不可由玩家修改 · <a href="/debug">开发者日记入口</a></span><span>状态版本 {revision}{!connected&&<em> · 连接断开，自动重连中…</em>}</span></footer>
  </main>;
}

function AgentConnection({session,revision,state}:{session:ObserverSnapshot["session"];revision:number;state:GameState}){return <section className="panel agentConnection"><div className="sectionTitle"><h2>玩家 · {state.playerName}</h2><span className={session.status}>{session.status==="online"?"已上线":"已下线"}</span></div><div className="connectionState"><i/><div><b>{session.status==="online"?state.playerName:`等待${state.playerName}`}</b><p>{session.status==="online"?`${state.playerName}正通过本地协议读取状态并安排行动。`:"网页只负责观察，不会替玩家做决定。"}</p></div></div><code>POST /api/agent/session</code><div className="reserve">当前状态版本 <b>{revision}</b></div></section>}

function PetStatusCard({state}:{state:GameState}){const journey=state.activeJourney;const route=journey?getRoute(journey.routeId):null;const stage={outbound:"去程路上",play:"正在游玩",overnight:"今夜外宿",return:"返程路上"};const location=journey?`${stage[journey.stage]} · ${getPlace(journey.destinationId).name}`:state.positionId?getPlace(state.positionId).name:"尚未安家";const activity=state.pendingActions.length?`等待结算：${state.pendingActions.at(-1)!.option.label}`:journey?stage[journey.stage]:state.activeEvents.length?`正在经历：${state.activeEvents[0].name}`:state.condition==="恢复中"?"在小窝恢复":"在小窝自由活动";const needs=(["health","mood","energy","satiety"] as const).map(key=>({key,label:stats[key][0],value:state.stats[key]})).sort((a,b)=>a.value-b.value);const urgent=state.condition!=="健康"?`需优先处理：${state.condition}`:needs[0].value<75?`${needs[0].label}最需关注 · ${needs[0].value}`:"当前没有紧急需求";const overall=journey?"正在出游":state.condition!=="健康"?state.condition:needs[0].value<40?"需要照料":needs[0].value<65?"有点欠状态":"状态稳定";const minReturn=journey&&route?(journey.stage==="outbound"?journey.remainingTurns+1+route.travelTurns:journey.stage==="play"||journey.stage==="overnight"?1+route.travelTurns:journey.remainingTurns):null;return <section className={`petNow ${journey?"isAway":state.condition!=="健康"?"needsCare":""}`} aria-label="宠物当前状态"><div className="nowSummary"><div><span className="eyebrow">PET RIGHT NOW</span><h2>{state.petName}现在：{overall}</h2><p><b>位置</b>{location}</p><p><b>正在做</b>{activity}</p></div><div className="urgentNeed"><span>当前重点</span><strong>{urgent}</strong>{minReturn!==null?<p><b>最早 {minReturn} 轮回家</b><small>可能因外宿、意外、天气或{state.playerName}改变安排而延长</small></p>:<p><b>{state.condition}</b><small>{state.weather} · {state.moodSignal}</small></p>}</div></div><div className="nowStats">{Object.entries(stats).map(([key,[label,color]])=>{const statKey=key as keyof typeof state.stats;const value=state.stats[statKey];const change=state.previousStats?value-state.previousStats[statKey]:0;return <div className="nowStat" key={key}><div><span>{label}</span><b>{value}</b><em className={change>0?"up":change<0?"down":""}>{state.previousStats?(change>0?`+${change}`:String(change)):"初始"}</em></div><div className="track"><i style={{width:`${value}%`,background:color}}/></div></div>})}</div></section>}

function Room({state,thinking}:{state:GameState;thinking:boolean}){const journey=state.activeJourney;const stageNames={outbound:"去程",play:"游玩",overnight:"外宿",return:"返程"};return <><div className="sceneHeader"><span className={`liveDot ${journey?"away":""}`}/>{journey?`旅途中 · ${stageNames[journey.stage]} · 前往${getPlace(journey.destinationId).name}`:state.positionId?`位于${getPlace(state.positionId).name}`:`${state.playerName}正在挑选住址`}<small>{state.condition}</small></div><div className={`room ${journey?"emptyNest":""}`}><div className="window"><i/><i/><b/></div><div className="shelf"><span>📕</span><span>🫙</span><span>🕯️</span></div><div className="rug"/>{!journey&&<div className={`pet ${thinking?"thinking":""}`}><div className="ear left"/><div className="ear right"/><div className="face"><i className="eye left"/><i className="eye right"/><i className="mouth"/></div><div className="body"/><div className="tail"/></div>}{journey&&<div className="awayCard"><span>小窝空着</span><b>{stageNames[journey.stage]}还需 {journey.remainingTurns} 轮</b><p>回到这里才算本次出游结束</p></div>}<div className="speech">{thinking?`${state.playerName}正在比较后果……`:state.publicLog[0].text}</div></div></>}

function DecisionBoard({state}:{state:GameState}){const reason={health:"健康优先",energy:"保留精力",mood:"回应心情",supplies:"补足物资",budget:"控制预算",wish:"评估愿望",travel:"推进旅行",event:"处理事件",explore:"继续观察",settle:"安顿起点"};const pending=state.pendingActions.length>0;const decisions=pending?state.pendingActions.map(item=>({id:item.id,actionLabel:item.option.label,reasonCode:item.decision.reasonCode,note:item.decision.note,cost:item.option.cost})):state.lastSettledDecisions;return <section className="decisionBoard"><div className="decisionHead"><div><span className="eyebrow">PLAYER DECISION</span><h2>{pending?`${state.playerName}这轮安排了什么`:`${state.playerName}上轮是怎么选的`}</h2></div><span>{pending?"等下轮结算":"后果已揭晓"}</span></div><div className="autoSignals"><b>系统提供的已知信息</b><span>健康 {state.stats.health}</span><span>精力 {state.stats.energy}</span><span>心情 {state.stats.mood}</span><span>余额 {state.money}</span><span>{state.weather}</span>{state.wish&&!state.wish.considered&&<span>有新愿望</span>}</div>{decisions.length?<div className="decisionCards">{decisions.map((item,index)=><article key={item.id}><i>{index+1}</i><div><b>{item.actionLabel}</b><span>{reason[item.reasonCode]}</span><p>{item.note||"无额外备注"}</p></div><em>{item.cost?`预留 ${item.cost}`:"无费用"}</em></article>)}</div>:<p className="empty">等待{state.playerName}上线后做出第一个决定。</p>}<p className="generatedNote">{state.playerName}只能从合法动作中选择；状态、费用和后果全由系统结算。</p></section>}

function SessionRecap({state}:{state:GameState}){const facts=state.publicLog.filter(entry=>entry.turn===state.clock.turn&&entry.category!=="系统").slice().reverse();return <section className="sessionRecap"><div className="recapHead"><div><span className="eyebrow">SINCE LAST LOGIN</span><h2>这次上线发生了什么</h2></div><b>{facts.length} 件事</b></div>{facts.length?<div className="recapTimeline">{facts.map((entry,index)=><article key={`${entry.id}-${index}`}><i>{index+1}</i><div><span>{entry.category}·{entry.title}</span><p>{entry.text}</p>{entry.deltas&&<small>{Object.entries(entry.deltas).map(([key,value])=>`${stats[key as keyof typeof stats]?.[0]??key} ${Number(value)>0?"+":""}${value}`).join(" · ")}</small>}</div>{entry.moneyDelta!==undefined&&<strong className={entry.moneyDelta>=0?"positive":"negative"}>{entry.moneyDelta>=0?"+":""}{entry.moneyDelta}</strong>}</article>)}</div>:<p className="empty">这是本轮安排阶段，后果要到下次上线才显示。</p>}</section>}

function TravelChronicles({state,onComment}:{state:GameState;onComment:(id:string,text:string)=>void}){const [drafts,setDrafts]=useState<Record<string,string>>({});const stage={outbound:"去程",play:"游玩",overnight:"外宿",return:"返程"};return <div className="listView tripView"><div className="mapTitle"><div><span className="eyebrow">TRAVEL CHRONICLES</span><h2>旅途小记</h2></div><p>只有回到小窝后才会归档，每轮事实与{state.playerName}的处理都保留。</p></div>{state.activeJourney&&<div className="activeTrip"><span>正在进行</span><b>{getPlace(state.activeJourney.destinationId).name} · {stage[state.activeJourney.stage]}</b><p>已记录 {state.activeJourney.moments.length} 条，回家后生成完整小记。</p></div>}{state.travelChronicles.length?state.travelChronicles.map(entry=><article className="chronicle" key={entry.id}><header><div><span>第 {entry.startedTurn}–{entry.endedTurn} 轮</span><h3>{entry.title}</h3></div><b>{entry.moments.length} 条行程</b></header><p className="tripSummary">{entry.summary}</p><div className="momentList">{entry.moments.map((moment,index)=><div key={`${moment.turn}-${index}`}><i>{stage[moment.stage]}</i><span><b>第 {moment.turn} 轮 · {moment.title}</b><p>{moment.text}</p>{moment.agentHandling&&<small>{state.playerName}的处理：{moment.agentHandling}</small>}</span></div>)}</div><blockquote><b>{state.playerName}总结</b>{entry.agentSummary}</blockquote>{entry.comments.length>0&&<div className="tripComments">{entry.comments.map(comment=><p key={comment.id}><b>{state.petName}留言</b>{comment.text}</p>)}</div>}<form className="commentForm" onSubmit={event=>{event.preventDefault();const text=drafts[entry.id]??"";if(text.trim()){onComment(entry.id,text);setDrafts(d=>({...d,[entry.id]:""}));}}}><input aria-label={`给${entry.title}留言`} value={drafts[entry.id]??""} onChange={event=>setDrafts(d=>({...d,[entry.id]:event.target.value}))} maxLength={180} placeholder="在这次小记下留言……"/><button>留言</button></form></article>):<p className="empty roomy">还没有完成的旅行，第一次回家后会在这里出现。</p>}</div>}

function WorldMap({state}:{state:GameState}){return <div className="mapView"><div className="mapTitle"><div><span className="eyebrow">STRUCTURED WORLD GRAPH</span><h2>周边地图 · {PLACES.length} 地点</h2></div><p>{state.homeChoiceReason||"拖动地图查看城镇枢纽与偏僻支线。"}</p></div><div className="mapField"><div className="mapCanvas"><svg className="mapRoutes" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="路线图">{ROUTES.map(route=>{const a=PLACES.find(p=>p.id===route.from)!,b=PLACES.find(p=>p.id===route.to)!;return <g key={route.id}><line className="routeLine" x1={a.x} y1={a.y} x2={b.x} y2={b.y}/><title>{`${route.distance}km · ${route.travelTurns}轮 · 风险${Math.round(route.risk*100)}%`}</title></g>})}</svg>{PLACES.map(place=><div key={place.id} className={`mapNode ${state.homeId===place.id?"home":""} ${state.positionId===place.id?"here":""}`} style={{left:`${place.x}%`,top:`${place.y}%`}}><b>{place.name}</b><span>房费 {place.housingCost}</span>{state.homeId===place.id&&<em>住址</em>}</div>)}</div></div><div className="mapLegend"><span><i className="homeDot"/>{state.playerName}选择的住址</span><span>密集连线是城镇枢纽，稀疏支线通向偏僻地点</span></div></div>}
function PublicLog({state,ready}:{state:GameState;ready:boolean}){return <div className="listView"><div className="mapTitle"><div><span className="eyebrow">IMMUTABLE FACTS</span><h2>宠物日志</h2></div><p>只记录程序结算后的客观事实。</p></div>{state.publicLog.map((entry,index)=><article className="logEntry" key={`${entry.id}-${index}`}><time>{ready?formatTime(entry.at):"--:--"}</time><span className={`category c${entry.category}`}>{entry.category}</span><div><h3>{entry.title}</h3><p>{entry.text}</p></div>{entry.moneyDelta&&<b className={entry.moneyDelta>0?"positive":"negative"}>{entry.moneyDelta>0?"+":""}{entry.moneyDelta}</b>}</article>)}</div>}
function Ledger({state,ready}:{state:GameState;ready:boolean}){return <div className="listView"><div className="mapTitle"><div><span className="eyebrow">LOCAL ECONOMY</span><h2>照料账本</h2></div><p>住房、收入、采购、医疗与差旅全部可追溯。</p></div><div className="moneySummary"><div><span>余额</span><b>◉ {state.money}</b></div><div><span>应急目标</span><b>{state.strategy.reserveTarget}</b></div><div><span>待偿</span><b>{state.debt}</b></div></div>{state.ledger.length?<div className="ledgerRows">{state.ledger.map(entry=><div key={entry.id}><time>{ready?formatTime(entry.at):"--:--"}</time><span>{entry.category}</span><p>{entry.note}</p><b className={entry.amount>0?"positive":"negative"}>{entry.amount>0?"+":""}{entry.amount}</b><em>余 {entry.balance}</em></div>)}</div>:<p className="empty roomy">{state.playerName}选址后，第一笔住房支出会记录在这里。</p>}</div>}
function Collection({state}:{state:GameState}){return <div className="listView"><div className="mapTitle"><div><span className="eyebrow">DISCOVERIES & ITEMS</span><h2>图鉴与道具</h2></div><p>{state.visitedPlaces.length} / {PLACES.length} 地点</p></div>{state.inventory.length>0&&<div className="souvenirs"><b>{state.playerName}可安排使用</b>{state.inventory.map(item=><span key={item.id}>{item.name} · {item.usesRemaining}/{item.maxUses} 次</span>)}</div>}{state.keepsakes.length>0&&<div className="keepsakeList"><b>私藏信件</b>{state.keepsakes.map(item=><article key={item.id}><span>{item.sourcePlaceName} · 第 {item.acquiredTurn} 轮</span><h3>{item.name}</h3><p>{item.body}</p></article>)}</div>}<div className="collectionGrid">{PLACES.map(place=><div key={place.id} className={state.visitedPlaces.includes(place.id)?"found":"locked"}><span>{state.visitedPlaces.includes(place.id)?"●":"○"}</span><b>{state.visitedPlaces.includes(place.id)?place.name:"未发现地点"}</b><p>{state.visitedPlaces.includes(place.id)?place.summary:`等待${state.playerName}安排一次合适的旅行。`}</p></div>)}</div>{state.collections.length>0&&<div className="souvenirs"><b>已发现物资</b>{state.collections.map(item=><span key={item}>{item}</span>)}</div>}</div>}
const formatTime=(at:number)=>new Date(at).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});
